objects/Account.object
<CustomObject>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <label>Toggl Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/Toggl_Custom_Log__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Toggl Custom Log</label>
    <nameField>
        <displayFormat>TCL-{00000000}</displayFormat>
        <label>Toggl Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toggl Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GAAP_Class__c</fullName>
        <label>GAAP Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work in Progress</fullName>
                </value>
                <value>
                    <fullName>Cost of Revenue</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>General &amp; Administrative</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Development</fullName>
                </value>
                <value>
                    <fullName>2.0 Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ToggleAccount__mdt.object
<CustomObject>
    <fields>
        <fullName>API_Token__c</fullName>
        <label>API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_User_Profile_Name__c</fullName>
        <label>New User Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workspace_ID__c</fullName>
        <label>Workspace ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>ToggleAccount</label>
    <pluralLabel>ToggleAccounts</pluralLabel>
</CustomObject>

classes/TogglGAAPClassBatch.cls
/*******************************************************************************************************
*    Name:  TogglGAAPClassBatch.cls
*    Author: OMNIVO DIGITAL (www.omnivodigital.com) 
*    Date:  9/24/2018
*    Modified Date: 10/1/2018
*
*    Test class:TogglGAAPClassTest.cls
*    Update GAAP Class for all Toggl projects
*    TogglGAAPClassBatch d = new TogglGAAPClassBatch(); 
*    database.executebatch(d, 10);
********************************************************************************************************/

global with sharing class TogglGAAPClassBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    global TogglGAAPClassBatch(){
    }
     
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('SELECT Id, Project_Name__c, Account__r.Name FROM Toggl_Time_Entry__c WHERE Project_Name__c != NULL AND Project__c = NULL');
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope)
    {
        
        Set<String> projectNames = new Set<String>();
        for (Toggl_Time_Entry__c tte : (List<Toggl_Time_Entry__c>)scope) {
            projectNames.add(tte.Project_Name__c);
            System.debug(tte.Id);
        }
            
        Map<String, TASKRAY__Project__c> TASKRAYProjectsMap = new Map<String, TASKRAY__Project__c>();
        Map<String, String> TASKRAYProjectsStageMap = new Map<String, String>();
        // Get Existing Task RAY Projects
        List<TASKRAY__Project__c> existingTASKRAYProjects = [SELECT Id, Name, TASKRAY__trOpportunity__c, TASKRAY__trOpportunity__r.StageName FROM TASKRAY__Project__c WHERE Name IN :projectNames];
        for (TASKRAY__Project__c existingProject : existingTASKRAYProjects) {
            TASKRAYProjectsMap.put(existingProject.Name, existingProject);
            TASKRAYProjectsStageMap.put(existingProject.Name, existingProject.TASKRAY__trOpportunity__r.StageName);
        }
        
        for (Toggl_Time_Entry__c tte : (List<Toggl_Time_Entry__c>)scope) {
            String projectName = tte.Project_Name__c;
            String accountName = tte.Account__r.Name;
            String opportunityStageName = '';
            String GAAPClass = '';
            String taskrayType = '';
            
            
            if (TASKRAYProjectsMap.containsKey(projectName))
                opportunityStageName = TASKRAYProjectsStageMap.get(projectName);
            
            if(!String.isEmpty(projectName) && !String.isEmpty(opportunityStageName) && !String.isEmpty(accountName))
            {
                if(projectName.contains('-'))
                {
                    String[] splitProject = projectName.split('-');
                    if(splitProject[2] != null && splitProject[2] != '')
                    {
                        if(splitProject[2].length() == 3) taskrayType = 'PICO ID';
                        if(splitProject[2].length() == 4) taskrayType = 'Contract ID';
                    }
                }
                
                if(accountName != 'Doctor Evidence' && accountName != 'DRE Tech')
                {
                    if(taskrayType == 'Contract ID' || taskrayType == 'PICO ID')
                    {
                        if(opportunityStageName != 'Closed Won' && opportunityStageName != 'Closed Lost') GAAPClass = 'Work In Progress';  
                        if(opportunityStageName == 'Closed Won') GAAPClass = 'Cost of Revenue';
                        if(opportunityStageName == 'Closed Lost') GAAPClass = 'Sales & Marketing';
                    }
                } else {
                    if(accountName == 'Doctor Evidence')
                    {
                        if(projectName == 'CE Admin/Internal' || projectName == 'CS Admin/Internal') {
                            GAAPClass = 'Sales & Marketing';
                        } else { GAAPClass = 'General & Administrative'; }
                    } else {
                        if(accountName == 'DRE Tech')
                        {
                            if(projectName == 'DRE Tech_Admin/Internal' || projectName == 'DRE Tech_Platform Maintenance') {
                                GAAPClass = 'Research & Development';
                            } else { GAAPClass = '2.0 Cap'; }
                        }
                    }
                }
            }
            Id projectId = null;
            Id opportunityId = null;
            if(TASKRAYProjectsMap.containsKey(projectName))
            {
                TASKRAY__Project__c trp = TASKRAYProjectsMap.get(projectName);
                if(trp != null)
                {
                    projectId = TASKRAYProjectsMap.get(projectName).Id;
                    opportunityId = TASKRAYProjectsMap.get(projectName).TASKRAY__trOpportunity__c;
                }
            }
            
            
            tte.Project__c = projectId;
            tte.Opportunity__c = opportunityId;
            tte.GAAP_Class__c = GAAPClass;
            
        }
        
        update scope;
        
        /*List<ToggleAccount__mdt> creds = [SELECT Username__c, Password__c, API_Token__c, Workspace_ID__c, New_User_Profile_Name__c FROM ToggleAccount__mdt];
        if (creds.isEmpty()) {
            throw new RequiredFeatureMissingException('Please add Toggle credentials in custom metadata');
        }

        String username = creds[0].Username__c;
        String workspaceId = creds[0].Workspace_ID__c;
        
        
        
        Map<String, TASKRAY__Project__c> TASKRAYProjectsMap = new Map<String, TASKRAY__Project__c>();
        Map<String, String> TASKRAYProjectsStageMap = new Map<String, String>();
        // Get Existing Task RAY Projects
        List<TASKRAY__Project__c> existingTASKRAYProjects = [SELECT Id, Name, TASKRAY__trOpportunity__c, TASKRAY__trOpportunity__r.StageName FROM TASKRAY__Project__c];
        for (TASKRAY__Project__c existingProject : existingTASKRAYProjects) {
            TASKRAYProjectsMap.put(existingProject.Name, existingProject);
            TASKRAYProjectsStageMap.put(existingProject.Name, existingProject.TASKRAY__trOpportunity__r.StageName);
        }
        
       
        // Get Existing Toggl Time Entries where start date is between sinceDate and untilDate and that don't have an assigned Project or Opportunity
        List<Toggl_Time_Entry__c> ExistingTogglTimeEntries = [SELECT Id, Toggl_Id__c, Project_Name__c, Project__c, Opportunity__c, GAAP_Class__c FROM Toggl_Time_Entry__c WHERE Start_Date__c >=: sinceDate AND Start_Date__c <=: untilDate AND (Project__c = NULL OR Opportunity__c = NULL)];
        Map<String, Toggl_Time_Entry__c> TogglTimeEntriesMap = new Map<String, Toggl_Time_Entry__c>();
        for(Toggl_Time_Entry__c tte: ExistingTogglTimeEntries)
        {
            TogglTimeEntriesMap.put(tte.Toggl_Id__c, tte);
        }
        
        // List to keep the Toggl time entries to update
        List<Toggl_Time_Entry__c> tteToUpdate = new List<Toggl_Time_Entry__c>();
        
        // Iterate through pages and get all toggle time entries
        for(String spage : pages) 
        {
            Integer page = Integer.valueOf(spage);
            TogglToSalesforce TTS = new TogglToSalesforce();
            String requestUrl = apiReporstsUrl+ '/details?workspace_id=' + workspaceId + '&user_agent=' + username
                + '&since=' + sinceString + '&until=' + untilString + '&page=' + String.valueOf(page);
            HttpResponse resp = TTS.invokeCallout(requestUrl, '', 'GET', new Map<String, String>());
            
            if (resp.getStatusCode() == 400) {
                resp = TTS.invokeCallout(requestUrl, '', 'GET', new Map<String, String>());
    
                if (resp.getStatusCode() == 400) {
                    List<Toggl_Custom_Log__c> sameLogs = [SELECT Id FROM Toggl_Custom_Log__c WHERE URL__c = :requestUrl];
    
                    if (sameLogs.isEmpty()) {
                        Toggl_Custom_Log__c customLog = new Toggl_Custom_Log__c(
                            URL__c = requestUrl
                        );
                        insert customLog;
                    }
                    return;
                }
            }
            
            TogglToSalesforce.ReportDetailsWrapper reportDetails = (TogglToSalesforce.ReportDetailsWrapper) JSON.deserialize(resp.getBody(), TogglToSalesforce.ReportDetailsWrapper.class);
            
            // iterate through retrived time entries
            for (TogglToSalesforce.TimeEntryWrapper timeEntry : reportDetails.data) {
                // get project name
                String projectName = (timeEntry.project).trim();
                if(projectName.contains('|'))
                {
                    String[] pName = projectName.split('\\|');
                    projectName = (pName[0]).trim();
                }
                String accountName = timeEntry.client;
                String opportunityStageName = '';
                String GAAPClass = '';
                String taskrayType = '';
                
                    
                if(TASKRAYProjectsMap.containsKey(projectName))
                    opportunityStageName = TASKRAYProjectsStageMap.get(projectName);
                
                if(!String.isEmpty(projectName) && !String.isEmpty(opportunityStageName) && !String.isEmpty(accountName))
                {
                    if(projectName.contains('-'))
                    {
                        String[] splitProject = projectName.split('-');
                        if(splitProject[2] != null && splitProject[2] != '')
                        {
                            if(splitProject[2].length() == 3) taskrayType = 'PICO ID';
                            if(splitProject[2].length() == 4) taskrayType = 'Contract ID';
                        }
                    }
                    
                    if(accountName != 'Doctor Evidence' && accountName != 'DRE Tech')
                    {
                        if(taskrayType == 'Contract ID' || taskrayType == 'PICO ID')
                        {
                            if(opportunityStageName != 'Closed Won' && opportunityStageName != 'Closed Lost') GAAPClass = 'Work In Progress';  
                            if(opportunityStageName == 'Closed Won') GAAPClass = 'Cost of Revenue';
                            if(opportunityStageName == 'Closed Lost') GAAPClass = 'Sales & Marketing';
                        }
                    } else {
                        if(accountName == 'Doctor Evidence')
                        {
                            if(projectName == 'CE Admin/Internal' || projectName == 'CS Admin/Internal') {
                                GAAPClass = 'Sales & Marketing';
                            } else { GAAPClass = 'General & Administrative'; }
                        } else {
                            if(accountName == 'DRE Tech')
                            {
                                if(projectName == 'DRE Tech_Admin/Internal' || projectName == 'DRE Tech_Platform Maintenance') {
                                    GAAPClass = 'Research & Development';
                                } else { GAAPClass = '2.0 Cap'; }
                            }
                        }
                    }
                }
                Id projectId = null;
                Id opportunityId = null;
                if(TASKRAYProjectsMap.containsKey(projectName))
                {
                    TASKRAY__Project__c trp = TASKRAYProjectsMap.get(projectName);
                    if(trp != null)
                    {
                        projectId = TASKRAYProjectsMap.get(projectName).Id;
                        opportunityId = TASKRAYProjectsMap.get(projectName).TASKRAY__trOpportunity__c;
                    }
                }
                
                
                String stId = String.valueOf(timeEntry.id);
                // update existing toggl time entry
                if(TogglTimeEntriesMap.containsKey(stId))
                {
                    Toggl_Time_Entry__c tte = TogglTimeEntriesMap.get(stId);
                    tte.Project_Name__c = projectName;
                    tte.Project__c = projectId;
                    tte.Opportunity__c = opportunityId;
                    tte.GAAP_Class__c = GAAPClass;
                    tteToUpdate.add(tte);
                }
                
            }
        }
        if(tteToUpdate.size() > 0)
            update tteToUpdate;*/
    }
    
    

    global void finish(Database.BatchableContext bc)
    {
        
    }
}