objects/Account.object
<CustomObject>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Archived_Date__c</fullName>
        <label>Archived Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Client_Delivered_Date__c</fullName>
        <inlineHelpText>The earliest date on which a client is sent their final deliverable(s).</inlineHelpText>
        <label>Client Delivered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Feedback_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Kick_Off_Meeting__c</fullName>
        <inlineHelpText>The date on which the client kick off meeting actually occurred</inlineHelpText>
        <label>Client Kick Off Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deliverable_Components__c</fullName>
        <label>Deliverable Components</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all</fullName>
                </value>
                <value>
                    <fullName>2 - Unsatisfactory</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfactory</fullName>
                </value>
                <value>
                    <fullName>5 - Completely</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deliverable_Satisfaction__c</fullName>
        <label>Deliverable Satisfaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all satisfied</fullName>
                </value>
                <value>
                    <fullName>2 - Not satisfied</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfied</fullName>
                </value>
                <value>
                    <fullName>5 - Very Satisfied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meet_Business_Objective__c</fullName>
        <label>Meet Business Objective</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all</fullName>
                </value>
                <value>
                    <fullName>2 - Unsatisfactory</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfactory</fullName>
                </value>
                <value>
                    <fullName>5 - Completely</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage_New__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - New Project Request</fullName>
                    <default>true</default>
                    <label>1 - New Project Request</label>
                </value>
                <value>
                    <fullName>2 - In Progress</fullName>
                </value>
                <value>
                    <fullName>3 - Delivered to Client</fullName>
                </value>
                <value>
                    <fullName>4 - Client Feedback Request</fullName>
                </value>
                <value>
                    <fullName>5 - Client Feedback Received</fullName>
                </value>
                <value>
                    <fullName>6 - Project Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Timeliness__c</fullName>
        <label>Project Timeliness</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all</fullName>
                </value>
                <value>
                    <fullName>2 - Unsatisfactory</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfactory</fullName>
                </value>
                <value>
                    <fullName>5 - Completely</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>Project requestor's comments received upon project closure.</description>
        <inlineHelpText>Project requestor's comments received upon project closure.</inlineHelpText>
        <label>Requestor's Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Auto_Creation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Toggl Auto-Creation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <label>Toggl Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_DRE_Again__c</fullName>
        <label>Use DRE Again</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all</fullName>
                </value>
                <value>
                    <fullName>2 - Unsatisfactory</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfactory</fullName>
                </value>
                <value>
                    <fullName>5 - Completely</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sub_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries (Sub-Project)</relationshipLabel>
        <relationshipName>Toggl_Time_Entries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TASKRAYProjectAllHandler.cls
/********************************************************************************************************
*    Handler class: TASKRAYProjectAllHandler.cls
*    Author:  
*    Date:  8/20/2018
*    
*    Trigger:  TASKRAYProjectAll.trigger
*    Test class: TASKRAYProjectAllHandlerTest.cls
********************************************************************************************************/

public class TASKRAYProjectAllHandler {
    //Handler for before insert methods
    public void onBeforeInsert(list<TASKRAY__Project__c> newList , map<id, TASKRAY__Project__c> newMap) {
        UpdateProjectStatge(newList, null, newMap, null);
        checkProjectName(newList,null, null);        
    }
    //Handler for after insert methods
    public void onAfterInsert(list<TASKRAY__Project__c> newList , map<id, TASKRAY__Project__c> newMap) {
        CreateToggleProjet(newList, null, newMap, null);
    }
    //Handler for before Update methods
    public void onBeforeUpdate(list<TASKRAY__Project__c> newList, map<id, TASKRAY__Project__c> newMap , map<id, TASKRAY__Project__c> oldMap) {
        UpdateProjectStatge(newList, null, newMap, oldMap);
        AutoArchiveTogglProject(newList, null, newMap, oldMap);
        checkProjectName(newList, 'isUpdate', oldMap);
    }
    //Handler for after Update methods
    public void onAfterUpdate(list<TASKRAY__Project__c> newList, map<id, TASKRAY__Project__c> newMap,  map<id, TASKRAY__Project__c> oldMap) {
        CreateToggleProjet(newList, null, newMap, oldMap);
        ChangeGAAPClassesBasedOnPOC(newList, oldMap);
    }

    //Handler for before Deletes methods
    //public void onBeforeDelete(list<TASKRAY__Project__c> oldList, map<id, TASKRAY__Project__c> oldMap) {}
    //Handler for after Deletes methods
    //public void onAfterDelete(list<TASKRAY__Project__c> oldList , map<id, TASKRAY__Project__c> oldMap) {}
    
    private static integer NumberOfCallouts = 45;
    
    private void ChangeGAAPClassesBasedOnPOC(List<TASKRAY__Project__c> newList, Map<id, TASKRAY__Project__c> oldMap) {
    	
    	List<TASKRAY__Project__c> pocList = new List<TASKRAY__Project__c>();
    	for (TASKRAY__Project__c newPrj : newList) {
    		TASKRAY__Project__c oldPrj = oldMap.get(newPrj.Id);
			if (newPrj.POC__c == 'POC' && oldPrj.POC__c != 'POC') {
				pocList.add(newPrj);
			}
			if (newPrj.POC__c == 'Not POC' && oldPrj.POC__c != 'Not POC') {
				pocList.add(newPrj); 
			}
    	}
    	
    	if (pocList.size() > 0) {
    		List<Toggl_Time_Entry__c> tes = [SELECT Id, Project_Name__c, Account__r.Name, Start_Date__c FROM Toggl_Time_Entry__c WHERE Project__c IN :pocList OR Sub_Project__r.TASKRAY__Project_Parent__c IN :pocList];
    		if (tes.size() > 0) {
    			TogglGAAPClassBatch.SetGAAPClass(tes, false);
    		}
    	}
    	
    }
    
    private void CreateToggleProjet(list<TASKRAY__Project__c>newList, list<TASKRAY__Project__c>oldList, map<id, TASKRAY__Project__c> newMap, map<id, TASKRAY__Project__c> oldMap) {
        Set<Id> TProjectIds = new Set<Id>();
        for(TASKRAY__Project__c proj : newList) {
            if(oldMap != null && oldMap.size() > 0)
            {
                TASKRAY__Project__c oldProject = oldMap.get(proj.Id);
                if( oldProject.Toggl_Auto_Creation_Approved__c == false && proj.Toggl_Auto_Creation_Approved__c == true)
                    TProjectIds.add(proj.Id);
            } else {
                if( proj.Toggl_Auto_Creation_Approved__c == true)
                    TProjectIds.add(proj.Id);
            }
        }
        
        if(TProjectIds.size() > 0)
        {
            
            // Limit of callouts per transaction
            Map<Integer, Set<Id>> SetsMap = new Map<Integer, Set<Id>>();
            
            Integer i = 0;
            Integer j = 1;
            Set<Id> newSet;
            for(Id s: TProjectIds)
            {
                if(i == 0)
                   newSet = new Set<Id>();
                if(i <= NumberOfCallouts) {
                   if(!SetsMap.containsKey(j))
                   {
                       newSet.add(s);
                       SetsMap.put(j, newSet);
                   } else {
                       Set<Id> existingSet = SetsMap.get(j);
                       existingSet.add(s);
                       SetsMap.put(j, existingSet);
                   }
                }
                i++;
                if(i == NumberOfCallouts) { 
                    j++;
                    i = 0;
                }
            }
           
            
            if(SetsMap.size() > 0)
            {
                for(Integer ii: SetsMap.KeySet())
                {
                    Set<Id> s = SetsMap.get(ii);
                    if(!Test.isRunningTest())
                        ToggleProjectCreation.CreateToggleProject(s);
                }
            }
            
        }
        
    }
    
    // Add Toggle Project to Archive (Active = false) when Salesforce TASKRAY__Project is archived
    private void AutoArchiveTogglProject(list<TASKRAY__Project__c>newList, list<TASKRAY__Project__c>oldList, map<id, TASKRAY__Project__c> newMap, map<id, TASKRAY__Project__c> oldMap) {
        Set<String> TProjectIds = new Set<String>();
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(TASKRAY__Project__c proj : newList) {
            TASKRAY__Project__c oldProject = oldMap.get(proj.Id);
            if (proj.Archived_Date__c != null && proj.Archived_Date__c != oldProject.Archived_Date__c) {
                if (proj.Toggl_Id__c != null && proj.Toggl_Id__c != '') {
                	TProjectIds.add(proj.Toggl_Id__c); 
                }else {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(new String[] { UserInfo.getUserEmail() });
                    mail.setSenderDisplayName('Salesforce');
                    mail.setSubject('Archived Project doesn\'t have a Toggl Id');
                    mail.setUseSignature(false);
                    mail.setHtmlBody('Project ' + proj.Name + ' could not be archived in Toggl because it doesn\'t have a Toggl Id.');
                    emails.add(mail);
                }
            }
        }
        
        if(TProjectIds.size() > 0)
        {
            //List<Toggl_Time_Entry__c> TogglTimeEntry = [SELECT Id, Toggl_Id__c FROM Toggl_Time_Entry__c WHERE Project__c IN: TProjectName];
            
            //Set<String> ToggleProgIds = new Set<String>();
            //for(Toggl_Time_Entry__c tte: TogglTimeEntry )
            //{
            //    ToggleProgIds.add(tte.Toggl_Id__c);
            //}
            
            // Limit of callouts per transaction
            Map<Integer, Set<String>> SetsMap = new Map<Integer, Set<String>>();
            if(TProjectIds.size() > 0)
            {
                Integer i = 0;
                Integer j = 1;
                Set<String> newSet;
                for(String s: TProjectIds)
                {
                    if(i == 0)
                       newSet = new Set<String>();
                    if(i <= NumberOfCallouts) {
                       if(!SetsMap.containsKey(j))
                       {
                           newSet.add(s);
                           SetsMap.put(j, newSet);
                       } else {
                           Set<String> existingSet = SetsMap.get(j);
                           existingSet.add(s);
                           SetsMap.put(j, existingSet);
                       }
                    }
                    i++;
                    if(i == NumberOfCallouts) { 
                        j++;
                        i = 0;
                    }
                }
            }
            
            if(SetsMap.size() > 0)
            {
                for(Integer i: SetsMap.KeySet())
                {
                    Set<String> s = SetsMap.get(i);
                    if(!Test.isRunningTest())
                        ToggleProjectUpdate.DeactivateToggleProject(s);
                }
            }
            
        }
        
        if (emails.size() > 0) {
            Messaging.sendEmail(emails);
        }
    }
    
    
    private void UpdateProjectStatge(list<TASKRAY__Project__c>newList, list<TASKRAY__Project__c>oldList, map<id, TASKRAY__Project__c> newMap, map<id, TASKRAY__Project__c> oldMap) {
        Date TodayDate = Date.Today();
        for(TASKRAY__Project__c proj : newList) {
            if(proj.Client_Kick_Off_Meeting__c <= TodayDate && proj.Client_Delivered_Date__c == null && proj.Project_Stage_New__c != '2 - In Progress')
                proj.Project_Stage_New__c = '2 - In Progress';
            if(proj.Client_Delivered_Date__c != null && proj.Project_Stage_New__c != '3 - Delivered to Client')
                proj.Project_Stage_New__c = '3 - Delivered to Client';
            if(proj.Client_Feedback_Requested__c == true)
                proj.Project_Stage_New__c = '4 - Client Feedback Request';
            if(!String.isEmpty(proj.Deliverable_Satisfaction__c) || !String.isEmpty(proj.Meet_Business_Objective__c)
            || !String.isEmpty(proj.Project_Timeliness__c) || !String.isEmpty(proj.Deliverable_Components__c)
            || !String.isEmpty(proj.Use_DRE_Again__c) || !String.isEmpty(proj.Request__c))
                proj.Project_Stage_New__c = '5 - Client Feedback Received';
        }
    }
     
    private void checkProjectName(list<TASKRAY__Project__c> newList, String triggerValue, map<Id,TASKRAY__Project__c> oldMap)
    {
        map<String, TASKRAY__Project__c> nameMap = new Map<String, TASKRAY__Project__c>(); 
       	
        //if inserting multiple objects, check to see if any have the same name
        for(TASKRAY__Project__c tpcTmp : newList)
        {
            if(triggerValue != 'isUpdate')
            {
                if(nameMap.containsKey(tpcTmp.Name))
                {
                    tpcTmp.addError('Project Name (PICO ID) Must be Unique');
                }
                else
                {
                    nameMap.put(tpcTmp.Name, tpcTmp);
                }      
            }
            else
            {
                //if updating, only interested to see if the name got updated
                if(tpcTmp.Name != oldMap.get(tpcTmp.Id).Name)
                {
                    if(nameMap.containsKey(tpcTmp.Name))
                    {
                        tpcTmp.addError('Project Name (PICO ID) Must be Unique');
                    }
                    else
                    {
                        nameMap.put(tpcTmp.Name, tpcTmp);
                    }     
                }
            }
        }//end for
        
        //check to see whether any of the project names already exists in the database and if so, display an error        
        List<TASKRAY__Project__c> tpcList = [Select Name from TASKRAY__Project__c where Name in :nameMap.keySet()];  
                 
        if(!tpcList.isEmpty())
        {
            for(TASKRAY__Project__c tpcTmp : tpcList)
            {
				if (nameMap.get(tpcTmp.Name) != null){
					TASKRAY__Project__c tpcFaulty = nameMap.get(tpcTmp.Name);
					tpcFaulty.addError('Project Name (PICO ID) Must be Unique');	
				}
            }//end for
        }        
    }
}