objects/Account.object
<CustomObject>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Archived_Date__c</fullName>
        <label>Archived Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Client_Delivered_Date__c</fullName>
        <inlineHelpText>The earliest date on which a client is sent their final deliverable(s).</inlineHelpText>
        <label>Client Delivered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Feedback_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Kick_Off_Meeting__c</fullName>
        <inlineHelpText>The date on which the client kick off meeting actually occurred</inlineHelpText>
        <label>Client Kick Off Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deliverable_Satisfaction__c</fullName>
        <label>Deliverable Satisfaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Not at all satisfied</fullName>
                </value>
                <value>
                    <fullName>2 - Not satisfied</fullName>
                </value>
                <value>
                    <fullName>3 - Neutral</fullName>
                </value>
                <value>
                    <fullName>4 - Satisfied</fullName>
                </value>
                <value>
                    <fullName>5 - Very Satisfied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage_New__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - New Project Request</fullName>
                    <default>true</default>
                    <label>1 - New Project Request</label>
                </value>
                <value>
                    <fullName>2 - In Progress</fullName>
                </value>
                <value>
                    <fullName>3 - Delivered to Client</fullName>
                </value>
                <value>
                    <fullName>4 - Client Feedback Request</fullName>
                </value>
                <value>
                    <fullName>5 - Client Feedback Received</fullName>
                </value>
                <value>
                    <fullName>6 - Project Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Project_Name__c</fullName>
        <inlineHelpText>Brief description of research question in the form of a title.</inlineHelpText>
        <label>Secondary Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Auto_Creation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Toggl Auto-Creation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <label>Toggl Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TASKRAYProjectAllHandlerTest.cls
@isTest
public class TASKRAYProjectAllHandlerTest {
    
    private static testmethod void testTASKRAYProjectAllInsert(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Client_Kick_Off_Meeting__c = (Date.Today()).addDays(-5);
        
        Test.StartTest();
            insert tProject;
        Test.StopTest();
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('2 - In Progress', currentTProject.Project_Stage_New__c);
       
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('1 - New Project Request', currentTProject.Project_Stage_New__c);
        
        Test.StartTest();
            currentTProject.Client_Kick_Off_Meeting__c = (Date.Today()).addDays(-5);
            update currentTProject;
        Test.StopTest();
        
        TASKRAY__Project__c currentTProjectUp = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('2 - In Progress', currentTProjectUp.Project_Stage_New__c);
        
        
    }
    
    
    private static testmethod void testTASKRAYProjectAllUpdate1(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('1 - New Project Request', currentTProject.Project_Stage_New__c);
        
        Test.StartTest();
            currentTProject.Client_Delivered_Date__c = (Date.Today()).addDays(-5);
            update currentTProject;
        Test.StopTest();
        
        TASKRAY__Project__c currentTProjectUp = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('3 - Delivered to Client', currentTProjectUp.Project_Stage_New__c);
        
        
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate2(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('1 - New Project Request', currentTProject.Project_Stage_New__c);
        
        Test.StartTest();
            currentTProject.Client_Feedback_Requested__c = true;
            update currentTProject;
        Test.StopTest();
        
        TASKRAY__Project__c currentTProjectUp = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('4 - Client Feedback Request', currentTProjectUp.Project_Stage_New__c);
        
        
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate3(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('1 - New Project Request', currentTProject.Project_Stage_New__c);
        
        Test.StartTest();
            currentTProject.Deliverable_Satisfaction__c = '4 - Satisfied';
            update currentTProject;
        Test.StopTest();
        
        TASKRAY__Project__c currentTProjectUp = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals('5 - Client Feedback Received', currentTProjectUp.Project_Stage_New__c);
        
        
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate4(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Secondary_Project_Name__c = 'Seconday Project Name';
        tProject.Toggl_Auto_Creation_Approved__c = true;
        
        Test.StartTest();
            insert tProject;
        Test.StopTest();
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate5(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Secondary_Project_Name__c = 'Seconday Project Name';
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Toggl_Auto_Creation_Approved__c  FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        
        Test.StartTest();
            currentTProject.Toggl_Auto_Creation_Approved__c = true;
            update currentTProject;
        Test.StopTest();
    }
    
    private static testmethod void testTASKRAYProjectAllUpdate7(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Secondary_Project_Name__c = 'Seconday Project Name';
        insert tProject;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Toggl_Auto_Creation_Approved__c  FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        Toggl_Time_Entry__c tpe = new Toggl_Time_Entry__c ();
        tpe.Toggl_Id__c = '222222';
        tpe.Project__c = currentTProject.Id;
        insert tpe;
        
        Test.StartTest();
            currentTProject.Archived_Date__c = Date.today();
            update currentTProject;
        Test.StopTest();
    }
    private static testmethod void testTASKRAYProjectAllUniqueName()
    {
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        List<TASKRAY__Project__c> tpList = new List<TASKRAY__Project__c>();
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'Test Name';
        tProject.Secondary_Project_Name__c = 'Seconday Project Name';
        tpList.add(tProject);
        
        TASKRAY__Project__c tProject1 = new TASKRAY__Project__c();
        tProject1.TASKRAY__trAccount__c = acc.Id;
        tProject1.Name = 'Test Name';
        tProject1.Secondary_Project_Name__c = 'Seconday Project Name';
        
        TASKRAY__Project__c tProject2 = new TASKRAY__Project__c();
        tProject2.TASKRAY__trAccount__c = acc.Id;
        tProject2.Name = 'Test Name1';
        tProject2.Secondary_Project_Name__c = 'Seconday Project Name';
        tpList.add(tProject2);
        
        insert tpList;
        
        Test.StartTest();
        
        try
        {
            insert tProject1;
        }
        catch(Exception e){}
        try
        {
            tProject2.Name = 'Test Name';
            update tproject2;
        }
        catch(Exception e){}
        
        
        Test.StopTest();
        
        List<TASKRAY__Project__c> testProjectList = [SELECT Id, Name FROM TASKRAY__Project__c WHERE Id in :tpList];
        Map<Id, TASKRAY__Project__c> testProjectMap = new Map<Id, TASKRAY__Project__c>(testProjectList);
        
        system.assertEquals(2, testProjectList.size());
        system.assertEquals('Test Name', testProjectMap.get(tProject.Id).Name);
        system.assertEquals('Test Name1', testProjectMap.get(tProject2.Id).Name);
    }

}