objects/Account.object
<CustomObject>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Num__c</fullName>
        <defaultValue>'NA'</defaultValue>
        <label>Invoice #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bob_Scott_Approved_Final_Contract_SOW__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bob or Scott Approved Final Contract/SOW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Managerial sales opportunity forecast override.</description>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Hub</fullName>
                    <default>true</default>
                    <label>Data Hub</label>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>DOC Label</fullName>
                </value>
                <value>
                    <fullName>DOC Track</fullName>
                </value>
                <value>
                    <fullName>GROWTH</fullName>
                </value>
                <value>
                    <fullName>IHME</fullName>
                </value>
                <value>
                    <fullName>ASCO DOC Search</fullName>
                </value>
                <value>
                    <fullName>Service Project Platform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Uploaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proposal Uploaded</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Auto_Creation_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Toggl Auto-Creation Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <label>Toggl Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GAAP_Class__c</fullName>
        <label>GAAP Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work in Progress</fullName>
                </value>
                <value>
                    <fullName>Cost of Revenue</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>General &amp; Administrative</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Development</fullName>
                </value>
                <value>
                    <fullName>2.0 Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityAllHandlerTest.cls
@isTest
public class OpportunityAllHandlerTest{
    

    private static testmethod void testOpportunityAllHandler0()
    {
        // Data Setup
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        // Run Code
        Test.startTest();

            Test.setMock(HttpCalloutMock.class, new HTTPMockCallout());

            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opp';
            opp.AccountId = acc.Id;
            opp.StageName = 'Capabilities Presentation';       
            opp.CloseDate = (Date.today()).addDays(6);
            opp.In_Forecast__c = true;
            opp.Toggl_Pre_Sale_Project_Approved__c = true;
            insert opp;

        Test.stopTest();

        // Verify Results
        // no verification needed since no modification happends in the Salesforce org
    }

    private static testmethod void testOpportunityAllHandler5()
    {
        // Data Setup
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';       
        opp.CloseDate = (Date.today()).addDays(6);
        opp.In_Forecast__c = true;
        opp.Toggl_Pre_Sale_Project_Approved__c = true;
        insert opp;

        TASKRAY__Project__c project = new TASKRAY__Project__c();
        project.TASKRAY__trOpportunity__c = opp.Id;
        project.Toggl_Id__c = 'test';
        project.Toggl_Auto_Creation_Approved__c = false;
        insert project;

        // Run Code
        Test.startTest();

            Test.setMock(HttpCalloutMock.class, new HTTPMockCallout());

            opp.Bob_Scott_Approved_Final_Contract_SOW__c = true;
            opp.Contract_Uploaded__c = true;
            opp.Proposal_Uploaded__c = true;
            opp.StageName = 'Closed Won'; 
            opp.CloseDate = (Date.today()).addDays(-1);
            update opp;

        Test.stopTest();

        // Verify Results
        // no verification needed since no modification happends in the Salesforce org
    }

    private static testmethod void testOpportunityAllHandler1(){
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
       
        opp.CloseDate = (Date.today()).addDays(6);
        insert opp;
        
        
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'sa4-test-WXYZ';
        insert tProject;
        
        Toggl_Time_Entry__c tte = new Toggl_Time_Entry__c();
        tte.Account__c = acc.Id;
        tte.Project_Name__c = 'sa4-test-project | toggle project name';
        tte.Start_Date__c = (Date.Today()).addDays(-60);
        tte.Project__c = tProject.Id;
        tte.Toggl_Id__c = '912345678';
        tte.Opportunity__c = opp.Id;
        insert tte;
        
        Opportunity opp1 = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id];
        opp1.StageName = 'Closed Lost';
        
        
        Test.StartTest();
            update opp1;
        Test.StopTest();
        
        Toggl_Time_Entry__c timeEntry = [SELECT Id, GAAP_Class__c  FROM Toggl_Time_Entry__c WHERE Id = :tte.Id];
        System.assertEquals('Sales & Marketing', timeEntry.GAAP_Class__c);
        
    }
    
    private static testmethod void testOpportunityAllHandler2(){
        
        Account acc = new Account();
        acc.Name = 'Doctor Evidence';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
       
        opp.CloseDate = (Date.today()).addDays(6);
        insert opp;
        
        
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'CE Admin/Internal';
        insert tProject;
        
        Toggl_Time_Entry__c tte = new Toggl_Time_Entry__c();
        tte.Account__c = acc.Id;
        tte.Project_Name__c = 'sa4-test-project | toggle project name';
        tte.Start_Date__c = (Date.Today()).addDays(-60);
        tte.Project__c = tProject.Id;
        tte.Toggl_Id__c = '912345678';
        tte.Opportunity__c = opp.Id;
        insert tte;
        
        Opportunity opp1 = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id];
        opp1.StageName = 'Closed Lost';
        
        
        Test.StartTest();
            update opp1;
        Test.StopTest();
        
        Toggl_Time_Entry__c timeEntry = [SELECT Id, GAAP_Class__c  FROM Toggl_Time_Entry__c WHERE Id = :tte.Id];
        System.assertEquals('Sales & Marketing', timeEntry.GAAP_Class__c);
        
    }
    
    private static testmethod void testOpportunityAllHandler3(){
        
        Account acc = new Account();
        acc.Name = 'DRE Tech';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
       
        opp.CloseDate = (Date.today()).addDays(6);
        insert opp;
        
        
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'DRE Tech_Admin/Internal';
        insert tProject;
        
        Toggl_Time_Entry__c tte = new Toggl_Time_Entry__c();
        tte.Account__c = acc.Id;
        tte.Project_Name__c = 'sa4-test-project | toggle project name';
        tte.Start_Date__c = (Date.Today()).addDays(-60);
        tte.Project__c = tProject.Id;
        tte.Toggl_Id__c = '912345678';
        tte.Opportunity__c = opp.Id;
        insert tte;
        
        Opportunity opp1 = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id];
        opp1.StageName = 'Closed Lost';
        
        
        Test.StartTest();
            update opp1;
        Test.StopTest();
        
        Toggl_Time_Entry__c timeEntry = [SELECT Id, GAAP_Class__c  FROM Toggl_Time_Entry__c WHERE Id = :tte.Id];
        System.assertEquals('Research & Development', timeEntry.GAAP_Class__c);
        
    }
    
    private static testmethod void testOpportunityAllHandler4(){
        
        Account acc = new Account();
        acc.Name = 'DRE Tech';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
       
        opp.CloseDate = (Date.today()).addDays(6);
        insert opp;
        
        
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'toggle project name';
        insert tProject;
        
        Toggl_Time_Entry__c tte = new Toggl_Time_Entry__c();
        tte.Account__c = acc.Id;
        tte.Project_Name__c = 'sa4-test-project | toggle project name';
        tte.Start_Date__c = (Date.Today()).addDays(-60);
        tte.Project__c = tProject.Id;
        tte.Toggl_Id__c = '912345678';
        tte.Opportunity__c = opp.Id;
        insert tte;
        
        Opportunity opp1 = [SELECT Id, StageName FROM Opportunity WHERE Id =: opp.Id];
        opp1.StageName = 'Closed Lost';
        
        
        Test.StartTest();
            update opp1;
        Test.StopTest();
        
        Toggl_Time_Entry__c timeEntry = [SELECT Id, GAAP_Class__c  FROM Toggl_Time_Entry__c WHERE Id = :tte.Id];
        System.assertEquals('2.0 Cap', timeEntry.GAAP_Class__c);
        
    }

    private static testmethod void testUpdateInvoicesOnClosedWon() {
        
        // Data setup
        Account acc = new Account();
        acc.Name = 'Test Account 212444';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp 422334';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
        opp.CloseDate = (Date.today()).addDays(6);
        opp.Contract_Uploaded__c = true;
        opp.Bob_Scott_Approved_Final_Contract_SOW__c = true;
        opp.In_Forecast__c = true;
        opp.Proposal_Uploaded__c = true;
        opp.Amount = 10000;
        insert opp;
        
        Invoice__c inv = new Invoice__c();
        inv.In_Forecast__c = true;
        inv.Invoice_Num__c = 'NA';
        inv.Opportunity__c = opp.Id;
        inv.Invoice_Amount__c = 1000;
        insert inv;
        
        // Run code
        Test.startTest();
        opp.StageName = 'Closed Won';
        update opp;
        Test.stopTest();
        
        // Verify results
        inv = [SELECT Invoice_Num__c FROM Invoice__c WHERE Id = :inv.Id];
        System.assertEquals('TBD', inv.Invoice_Num__c, 'Invoice number should now be "TBD" beause of the OpportunityAllHandler-UpdateInvoicesOnClosedWon method');
    }
    
    @isTest
    public static void testProductNameMappingInsert()
    {
        
        Account acc = new Account();
        acc.Name = 'DRE Tech';
        insert acc;
        
        Product2 prod = new Product2(Name = 'Focused Literature Reviews');
        insert prod;
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = test.getStandardPricebookId(),
                                                          Product2Id = prod.Id,
                                                          UnitPrice = 10000,
                                                          IsActive = true);
        insert standardPrice;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
        opp.Product_Category__c = 'Project';
        opp.CloseDate = (Date.today()).addDays(6);
        
        
        test.startTest();
        
        insert opp;  
        
        test.stopTest();
        
        Opportunity oppTest = [Select Id, Pricebook2Id from Opportunity where Id = :opp.Id];
        OpportunityLineItem oli = [Select Id, UnitPrice, Name from OpportunityLineItem where OpportunityId = :opp.Id];
        
        System.assertEquals(oppTest.Pricebook2Id, test.getStandardPricebookId());
        System.assertEquals(oli.UnitPrice, 10000);   
    }
    
    @isTest
    public static void testProductNameMappingUpdate()
    {
        Account acc = new Account();
        acc.Name = 'DRE Tech';
        insert acc;
        
        Product2 prod1 = new Product2(Name = 'Focused Literature Reviews');
        Product2 prod2 = new Product2(Name = 'GROWTH Basic Annual License');
        
        insert new List<Product2> { prod1, prod2 };
        
        /*insert new Pricebook2(
            Name = RevenueCalculationUtil.PRICEBOOK_NAME, 
            IsActive = true
        );*/
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = Test.getStandardPriceBookId(),
                                                          Product2Id = prod1.Id,
                                                          UnitPrice = 10000,
                                                          IsActive = true);
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = Test.getStandardPriceBookId(),
                                                          Product2Id = prod2.Id,
                                                          UnitPrice = 15000,
                                                          IsActive = true);
        
        insert new List<PricebookEntry> { standardPrice, standardPrice2 };
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = acc.Id;
        opp.StageName = 'New';
        opp.Product_Category__c = 'Project';
        opp.CloseDate = (Date.today()).addDays(6);
        
        insert opp;
        
        test.startTest();
        
        opp.Product_Category__c = 'GROWTH';
        RevenueCalculationUtil.isTriggerEnabled = false;
        update opp;

        test.stopTest();
        
        Opportunity oppTest = [Select Id, Pricebook2Id from Opportunity where Id = :opp.Id];
        system.debug('oli Query---'+ [Select Id, UnitPrice, Name from OpportunityLineItem where OpportunityId = :opp.Id]);
        OpportunityLineItem oli = [Select Id, UnitPrice, Name from OpportunityLineItem where OpportunityId = :opp.Id];
        
        System.assertEquals(oppTest.Pricebook2Id, test.getStandardPricebookId());
        System.assertEquals(oli.UnitPrice, 15000);
        
    }
}