objects/Account.object
<CustomObject>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Archived_Date__c</fullName>
        <label>Archived Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archived_Reason__c</fullName>
        <label>Archived Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete: Delivered (modified from original scope)</fullName>
                </value>
                <value>
                    <fullName>Complete: Delivered feasibility assessment</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Client strategy change</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Infeasible timeline</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Strategic internal decision</fullName>
                </value>
                <value>
                    <fullName>Contract Terminated</fullName>
                </value>
                <value>
                    <fullName>Contract Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Stage_New__c</fullName>
        <label>Project Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 - New Project Request</fullName>
                    <default>true</default>
                    <label>1 - New Project Request</label>
                </value>
                <value>
                    <fullName>2 - In Progress</fullName>
                </value>
                <value>
                    <fullName>3 - Delivered to Client</fullName>
                </value>
                <value>
                    <fullName>4 - Client Feedback Request</fullName>
                </value>
                <value>
                    <fullName>5 - Client Feedback Received</fullName>
                </value>
                <value>
                    <fullName>6 - Project Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <label>Toggl Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Toggl_Id__c</fullName>
        <externalId>true</externalId>
        <label>Toggl Id</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ToggleProjectUpdateTest.cls
/********************************************************************************************************
*    Handler class: ToggleProjectUpdateTest.cls
*    Author:  
*    Date:  8/22/2018
*    
*    Called from:  TASKRAYProjectAllHandler.trigger
*    Test class: ToggleProjectUpdate.cls
*    Mock Class: HTTPMockCallout.cls
********************************************************************************************************/

@isTest
public class ToggleProjectUpdateTest {

    private static testmethod void testToggleProjectUpdate(){
    
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Name = 'sa4-test-project';
        insert tProject;
        
        Toggl_Time_Entry__c tte = new Toggl_Time_Entry__c();
        tte.Account__c = acc.Id;
        tte.Project_Name__c = 'sa4-test-project | toggle project name';
        tte.Start_Date__c = (Date.Today()).addDays(-60);
        tte.Project__c = tProject.Id;
        tte.Toggl_Id__c = '912345678';
        insert tte;
        
        TASKRAY__Project__c currentTProject = [SELECT Id, TASKRAY__Status__c, Archived_Reason__c, Archived_Date__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        
        Test.StartTest();
            
            currentTProject.TASKRAY__Status__c = true;
            currentTProject.Archived_Reason__c = 'Contract Terminated';
            currentTProject.Archived_Date__c = datetime.now();
            
            update currentTProject;
            Test.setMock(HttpCalloutMock.class, new HTTPMockCallout());
        Test.StopTest();
        
        //TASKRAY__Project__c currentTProjectUp = [SELECT Id, Project_Stage_New__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        //System.assertEquals('Client Feedback Request', currentTProjectUp.Project_Stage_New__c);
        
        
    }
    
    private static testmethod void testToggleProjectUpdate1(){
         // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new HTTPMockCallout());
        // from the class that implements HttpCalloutMock. 
        Set<String> aId = new Set<String>();
        aId.add('912345678');
        ToggleProjectUpdate.DeactivateToggleProject(aId);
        
        // Verify response received contains fake values
        //String contentType = res.getHeader('Content-Type');
        //System.assert(contentType == 'application/json');
        //System.assertEquals(200, res.getStatusCode());
    }
}