objects/AdobeSign_template__mdt.object
<CustomObject>
    <fields>
        <fullName>Template_Id__c</fullName>
        <label>Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AdobeSign template</label>
    <pluralLabel>AdobeSign templates</pluralLabel>
</CustomObject>

objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Auto_Send_SOW__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do Not Auto-Send SOW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>PO No. Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PreferredVendorRequestHandler.cls
public class PreferredVendorRequestHandler {

    public static void SubmitAdobeSign(List<Preferred_Vendor_Request__c> newList, Map<Id, Preferred_Vendor_Request__c> oldMap) {
        
        AdobeSign_template__mdt setting = [SELECT Template_Id__c FROM AdobeSign_template__mdt LIMIT 1];
            
        for (Preferred_Vendor_Request__c newRecord : newList) {
            if (newRecord.Status__c == 'Approved' && (oldMap == null || oldMap.get(newRecord.Id).Status__c != 'Approved') && !newRecord.Do_Not_Auto_Send_SOW__c) {
        		Id agreementId = echosign_dev1.AgreementTemplateService.load(setting.Template_Id__c, newRecord.Id);
                echosign_dev1.EchoSignApiService.sendDocument(agreementId);
            }
        }
    }
    
}