objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Name__c</fullName>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Junction_Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <formula>Kbases__r.Extraction_Quantity__c</formula>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Junction Kbase</label>
    <nameField>
        <label>Case to Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Kbases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term_Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kbase</label>
    <nameField>
        <label>Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kbases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KbaseToJKbase_Test.cls
@isTest
public class KbaseToJKbase_Test {

     public static testMethod void testKbaseToJKbase(){
 
        //insert case
        Case c = new Case(Case_Name__c='Case12345');
        insert c;
        
        //set page reference
        //PageReference pageRef = new PageReference('/apex/KbasetoJKbase_EXT/?caseId='+c.Id);
        PageReference pageRef = Page.KbaseToJKbase_EXT;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('caseId', c.Id);
         
        //insert a Kbase
        Kbase__c kb = new Kbase__c(Name='Kbase12345', Extraction_Quantity__c=1, Extraction_Task_Description__c='Text');
        insert kb;
        
        //initialize Kbase for controller extension operations 
        Kbase__c kb2 = new Kbase__c();
                
        //instantiate and run method
        ApexPages.StandardController stdController = new ApexPages.StandardController(kb2);
        KbaseToJKbase_EXT ext = new KbaseToJKbase_EXT(stdController);   
        
        //test search methods
        //found case
        ext.kBaseRefId = 'kbase12345';
        ext.searchKbase();
        system.assertEquals(true, ext.foundExisting);
        //not found case
        ext.kBaseRefId = 'cant find it';
        ext.searchKbase();
        system.assertEquals(false, ext.foundExisting);
         
        //create the Kbase and Junction kbase
        ext.KbaseToJKbase();
        
        //assert that jKbase was created        
        system.debug(ext.caseId);
        List<Junction_Kbase__c> jKbaseList = [SELECT Id FROM Junction_Kbase__c WHERE Case__c =:ext.caseId LIMIT 1];        
        system.assertNotEquals(0, jKbaseList.size());
        
    } 
     
}