objects/Case.object
<CustomObject>
    <fields>
        <fullName>Digitized__c</fullName>
        <label># Digitized</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Junction_Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <formula>Kbases__r.Extraction_Quantity__c</formula>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kbases__c</fullName>
        <label>Ref ID</label>
        <referenceTo>Kbase__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LMS_Bucket__c</fullName>
        <label>LMS Bucket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Sub-Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Project must be a sub-project.</errorMessage>
            <filterItems>
                <field>TASKRAY__Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub-Project</value>
            </filterItems>
            <infoMessage>Please select a sub-project.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Junction_Kbases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Junction Kbase</label>
    <nameField>
        <label>Case to Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Kbases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term_Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kbase</label>
    <nameField>
        <label>Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kbases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Digitized__c</fullName>
        <inlineHelpText>[Calculated field] The number of junction kbases associated with a sub-project that are not rejected (i.e. the current number of references accepted during digitization).</inlineHelpText>
        <label># Digitized</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

classes/TaskRaySubprojectBatchTest.cls
/********************************************************************************************************
*    Name:  TaskRaySubprojectBatchTest.cls
*    Author:  
*    Date:  6/12/2018
*    
*    Scheduler class: TaskRaySubprojectScheduler.cls
*    Class: TaskRaySubprojectBatch.cls
********************************************************************************************************/
@isTest
public class TaskRaySubprojectBatchTest{
    
    private static testmethod void testTaskRaySubprojectBatch(){
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact cnt = new Contact(LastName = 'TestCon', AccountId = acc.Id);
        insert cnt;
        
        Case c  = new Case();
        //enter details
        c.AccountId = acc.Id;
        c.ContactId = cnt.Id;
        //c.RecordTypeId = rtId;
        c.Type = 'My Type';
        c.Origin = 'My Origin';
        c.Status = 'My Status';
        insert c;
        
        //insert Parent TASKRAY__Project__c
        TASKRAY__Project__c tpp = new TASKRAY__Project__c(Name = 'Parent Project', TASKRAY__trAccount__c = acc.Id);
        insert tpp;
        
        TASKRAY__Project__c tpc1 = new TASKRAY__Project__c(Name = 'Child Project 1', TASKRAY__Project_Parent__c = tpp.Id);
        insert tpc1;
        TASKRAY__Project__c tpc2 = new TASKRAY__Project__c(Name = 'Child Project 2', TASKRAY__Project_Parent__c = tpp.Id);
        insert tpc2;
        TASKRAY__Project__c tpc3 = new TASKRAY__Project__c(Name = 'Child Project 3', TASKRAY__Project_Parent__c = tpp.Id);
        insert tpc3;
        
        
        
        //insert Kbase
        Kbase__c kb = new Kbase__c(Name='Kbase12345', Extraction_Quantity__c=1, Extraction_Task_Description__c='Text');
        insert kb;
        
        //insert Junction Kbase
        List<Junction_Kbase__c> jkbList = new List<Junction_Kbase__c>();
        Junction_Kbase__c jkb1 = new Junction_Kbase__c(Name='jkb12345', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc1.Id, LMS_Bucket__c = 'Assigned');
        jkbList.add(jkb1);
        Junction_Kbase__c jkb2 = new Junction_Kbase__c(Name='jkb12346', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc2.Id, LMS_Bucket__c = 'On Hold');
        jkbList.add(jkb2);
        Junction_Kbase__c jkb3 = new Junction_Kbase__c(Name='jkb12347', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc2.Id, LMS_Bucket__c = 'Assigned');
        jkbList.add(jkb3);
        Junction_Kbase__c jkb4 = new Junction_Kbase__c(Name='jkb12348', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc3.Id, LMS_Bucket__c = 'On Hold');
        jkbList.add(jkb4);
        Junction_Kbase__c jkb5 = new Junction_Kbase__c(Name='jkb12349', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc3.Id, LMS_Bucket__c = 'Assigned');
        jkbList.add(jkb5);
        Junction_Kbase__c jkb6 = new Junction_Kbase__c(Name='jkb12350', Kbases__c = kb.Id, Case__c = c.Id, TaskRay_Project__c = tpc3.Id, LMS_Bucket__c = 'Rejected');
        jkbList.add(jkb6);

        insert jkbList;
        
        Test.StartTest();
            TaskRaySubprojectBatch obj = new TaskRaySubprojectBatch();
            DataBase.executeBatch(obj); 
            
            List<TASKRAY__Project__c> TASKRAYProjects = [SELECT Id, Digitized__c FROM TASKRAY__Project__c WHERE TASKRAY__Project_Parent__c =: tpp.Id];
            for(TASKRAY__Project__c ctp: TASKRAYProjects )
            {
                if(ctp.Id == tpc1.TASKRAY__Project_Parent__c )
                    System.assertEquals(1, ctp.Digitized__c);
                if(ctp.Id == tpc2.TASKRAY__Project_Parent__c )
                    System.assertEquals(2, ctp.Digitized__c);
                if(ctp.Id == tpc3.TASKRAY__Project_Parent__c  )
                    System.assertEquals(2, ctp.Digitized__c);
            }
            
            
        Test.StopTest();
    }
}