objects/ContractDrivers__c.object
<CustomObject>
    <fields>
        <fullName>DOC_Data_Configuration__c</fullName>
        <label>DOC Data Configuration</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Data_Licensing__c</fullName>
        <label>DOC Data Licensing</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Library_Configuration__c</fullName>
        <label>DOC Library Configuration</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Library_Licensing__c</fullName>
        <label>DOC Library Licensing</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Services__c</fullName>
        <label>Services</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>GAAP Multiple Element Allocation</description>
    <label>Contract Drivers</label>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Deferred_Revenue__c</fullName>
        <label>Deferred Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Monthly_Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Costs__c</fullName>
        <label>Cost of Revenue</label>
        <summarizedField>Department_Revenue_Schedule__c.Costs__c</summarizedField>
        <summaryForeignKey>Department_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monthly Revenue Schedules</relationshipLabel>
        <relationshipName>Monthly_Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <summarizedField>Product_Revenue_Schedule__c.Revenue__c</summarizedField>
        <summaryForeignKey>Product_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Monthly Revenue Schedule</label>
    <nameField>
        <displayFormat>MRS-{0}</displayFormat>
        <label>Monthly Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOC_Data_Configuration__c</fullName>
        <label>DOC Data Configuration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Data_Licensing__c</fullName>
        <label>DOC Data Licensing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Library_Configuration__c</fullName>
        <label>DOC Library Configuration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Library_Licensing__c</fullName>
        <label>DOC Library Licensing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Override_Allocations__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Allocations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Hub</fullName>
                    <default>true</default>
                    <label>Data Hub</label>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>DOC Label</fullName>
                </value>
                <value>
                    <fullName>DOC Track</fullName>
                </value>
                <value>
                    <fullName>GROWTH</fullName>
                </value>
                <value>
                    <fullName>IHME</fullName>
                </value>
                <value>
                    <fullName>ASCO DOC Search</fullName>
                </value>
                <value>
                    <fullName>Service Project Platform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Services_Percentage__c</fullName>
        <label>Services</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Services__c</fullName>
        <description>Services</description>
        <label>Services</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Subscription</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Services__c</fullName>
        <label>Services</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Monthly_Revenue_Schedule__r.Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Monthly_Revenue_Schedule__r.Opportunity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POC__c</fullName>
        <label>POC</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue_Schedule__c</fullName>
        <label>Monthly Revenue Schedule</label>
        <referenceTo>Monthly_Revenue_Schedule__c</referenceTo>
        <relationshipLabel>Product Revenue Schedules</relationshipLabel>
        <relationshipName>Product_Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Revenue Schedule</label>
    <nameField>
        <displayFormat>PRS-{0}</displayFormat>
        <label>Product Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RevenueCalculationTest.cls
/*   Name:          Revenue Calculation Test Class
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          8/17/2017
 *   Description:   Test class for Revenue Calculation.
 *                
 */

@isTest
private class RevenueCalculationTest {

    private static void init() {
        insert new ContractDrivers__c(
            Name = 'Data Hub',
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50,
            DOC_Library_Configuration__c = 0,
            DOC_Library_Licensing__c = 0,
            Services__c = 0,
            Subscription__c = 0
        );
        
        insert new Product2(
            Name = 'DOC Data Configuration'
        );
        
        insert new Pricebook2(
            Name = RevenueCalculationUtil.PRICEBOOK_NAME, 
            IsActive = true
        );
        
        insert new PricebookEntry(
            Product2Id = [SELECT Id FROM Product2 LIMIT 1].Id,
            Pricebook2Id = Test.getStandardPriceBookId(),
            UnitPrice = 100000,
            IsActive = false,
            UseStandardPrice = false
        );
        
        insert new PricebookEntry(
            Product2Id = [SELECT Id FROM Product2 LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            UnitPrice = 100000,
            IsActive = true,
            UseStandardPrice = false
        );
        
        insert new Account(
            Name = 'test'
        );
    }
    
    static testmethod void testCalculateOpportunity_Success() {
        init();
    
        Test.startTest();
        
        Opportunity testOpp = new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(3),
            Contract_End__c = Date.today().addMonths(9),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50,
            Use_New_Forecasting_Algorithm__c = false
        );
        insert testOpp;
        
        /*LEGACY*/
        //insert new Revenue_Schedule__c(Opportunity__c = [SELECT Id FROM Opportunity LIMIT 1].Id);
        
        Test.stopTest();
        
        System.assert(![SELECT Id FROM Product_Revenue_Schedule__c WHERE Monthly_Revenue_Schedule__r.Opportunity__c = :testOpp.Id].isEmpty(), 'Here must be generated revenue records.');
    }
    
    static testmethod void testCalculateOpportunity_Validated() {
        init();
    
        Test.startTest();
        
        Opportunity testOppStart = new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = null,
            Contract_End__c = Date.today().addMonths(9),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50
        );
        insert testOppStart;
        
        Opportunity testOppOffer = new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = null,
            Contract_Start__c = Date.today().addMonths(3),
            Contract_End__c = Date.today().addMonths(9),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50
        );
        insert testOppOffer;
        
        Test.stopTest();
        
        System.assert([SELECT Id FROM Product_Revenue_Schedule__c WHERE Monthly_Revenue_Schedule__r.Opportunity__c = :testOppStart.Id].isEmpty(), 'Here must not be any generated revenue records.');
        System.assert([SELECT Id FROM Product_Revenue_Schedule__c WHERE Monthly_Revenue_Schedule__r.Opportunity__c = :testOppOffer.Id].isEmpty(), 'Here must not be any generated revenue records.');
    }
    
    static testmethod void testCalculateRevenuePOC_Success() {
        init();
        
        insert new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(-2),
            Contract_End__c = Date.today().addMonths(4),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50,
            Use_New_Forecasting_Algorithm__c = false
        );
        
        List<Product_Revenue_Schedule__c> revenues = [
            SELECT POC__c, Revenue__c, Monthly_Revenue_Schedule__r.Costs__c
            FROM Product_Revenue_Schedule__c
            ORDER BY Date__c ASC
        ];
        System.assertEquals(6, revenues.size());
        
        Test.startTest();
        
        Product_Revenue_Schedule__c revToUpdate = revenues[0];
        revToUpdate.POC__c = 100;
        update revToUpdate;
        
        Test.stopTest();

        System.assertEquals(50000, [SELECT Amount FROM Opportunity LIMIT 1].Amount);
        System.assertEquals(1, [SELECT Id FROM OpportunityLineItem].size());
        System.assertEquals(50000, [SELECT TotalPrice FROM OpportunityLineItem LIMIT 1].TotalPrice);
        System.assertEquals(50000, [SELECT Revenue__c FROM Product_Revenue_Schedule__c WHERE Id = :revToUpdate.Id].Revenue__c);
    }
    
    static testmethod void testCalculateRevenueAmount_Success() {
        init();
        
        insert new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(-2),
            Contract_End__c = Date.today().addMonths(4),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50,
            Use_New_Forecasting_Algorithm__c = false
        );
        
        List<Product_Revenue_Schedule__c> revenues = [
            SELECT POC__c, Revenue__c, Monthly_Revenue_Schedule__r.Costs__c 
            FROM Product_Revenue_Schedule__c
            ORDER BY Date__c ASC
        ];
        System.assertEquals(6, revenues.size());
        
        Test.startTest();
        
        Product_Revenue_Schedule__c revToUpdate = revenues[0];
        revToUpdate.Revenue__c = 50000;
        update revToUpdate;
        
        List<Invoice__c> generatedInvoices = [SELECT Invoice_Amount__c FROM Invoice__c];
        System.assert(!generatedInvoices.isEmpty(), 'Invoices should be automatically generated.');
        
        generatedInvoices.get(0).Invoice_Amount__c = 10000;
        update generatedInvoices;
        
        Test.stopTest();
        
        System.assertEquals(100, [SELECT POC__c FROM Product_Revenue_Schedule__c WHERE Id = :revToUpdate.Id].POC__c);
    }
    
    static testmethod void testCalculateOpportunityLineItems_Success() {
        init();
        
        insert new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(-2),
            Contract_End__c = Date.today().addMonths(4),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50,
            Use_New_Forecasting_Algorithm__c = false
        );
        
        Test.startTest();
        
        delete new OpportunityLineItem(
            Id = [SELECT Id FROM OpportunityLineItem LIMIT 1].Id
        );
        
        Test.stopTest();
        
        System.assertEquals(0, [SELECT Amount FROM Opportunity LIMIT 1].Amount);
    }

    static testmethod void testInvoiceInitialCalculation_Success() {
        init();
        
        insert new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(-2),
            Contract_End__c = Date.today().addMonths(4),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = 50,
            DOC_Data_Licensing__c = 50
        );
        
        Test.startTest();
    
        Invoice__c invoiceToInsert = new Invoice__c(
            Opportunity__c = [SELECT Id FROM Opportunity LIMIT 1].Id,
            Invoice_Amount__c = 10000
        );
        insert invoiceToInsert;
        System.assertEquals(null, [SELECT Deferred_Revenue__c FROM Invoice__c WHERE Id = :invoiceToInsert.Id].Deferred_Revenue__c);
        
        update invoiceToInsert;
        System.assertEquals(10000, [SELECT Deferred_Revenue__c FROM Invoice__c WHERE Id = :invoiceToInsert.Id].Deferred_Revenue__c);
        
        Test.stopTest();
    }
    
    static testmethod void testCalculateOpportunityLineItemsEmptySetting_Success() {
        init();
        
        Test.startTest();
        
        insert new Opportunity(
            Name = 'test',
            CloseDate = Date.today(),
            Product_Category__c = 'Data Hub',
            Contract_Start__c = Date.today().addMonths(-2),
            Contract_End__c = Date.today().addMonths(4),
            Amount = 100000,
            StageName = 'Closed Lost',
            AccountId = [SELECT Id FROM Account LIMIT 1].Id,
            Pricebook2Id = [SELECT Id FROM Pricebook2 WHERE Name = :RevenueCalculationUtil.PRICEBOOK_NAME LIMIT 1].Id,
            DOC_Data_Configuration__c = null,
            DOC_Data_Licensing__c = null,
            Services_Percentage__c = 100,
            Override_Allocations__c = true,
            Use_New_Forecasting_Algorithm__c = false
        );
        
        Test.stopTest();
        
        System.assertEquals(0, [SELECT Amount FROM Opportunity LIMIT 1].Amount);
    }

}