objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Requester_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Email__c</fullName>
        <label>Requester Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Name__c</fullName>
        <label>Requester Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>Object created to receive client requests from the DOC Data portal.</description>
    <label>Project Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Project Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProjectRequestHandler.cls
public class ProjectRequestHandler {

    public static void matchContact(List<Project_Request__c> requestList) {
                
        List<Project_Request__c> updateRequestList = new List<Project_Request__c>();
        updateRequestList = [SELECT Id, Requester_Contact__c, Requester_Name__c, Requester_Email__c FROM Project_Request__c WHERE Id IN:requestList];
        
        List<Contact> contactList = new List<Contact>();
        
        Map<String, Project_Request__c> emailToRequest = New Map<String, Project_Request__c>();
        Map<Id, Contact> requestToContact = New Map<Id, Contact>();
        
        for(Project_Request__c pr: requestList){
            if(pr.Requester_Email__c != null){
            	emailToRequest.put(pr.Requester_Email__c.toLowerCase(), pr);    
            }   
        }
        
        for(Contact c: [SELECT Id, Email, FirstName, LastName FROM Contact WHERE Email IN:emailToRequest.keySet()]){
            	requestToContact.put(emailToRequest.get(c.email).id, c);		        		
        }
        
        Map<Id, Contact> requestToContactInsertMap = new Map<Id, Contact>();
        
        for(Project_Request__c pr: updateRequestList){
            if(requestToContact.get((pr.id))!= NULL){
            	pr.Requester_Contact__c = requestToContact.get(pr.id).id;		       
            }
            else {
                if (pr.Requester_Name__c != null) {
                    Contact c = new Contact(
                        FirstName = pr.Requester_Name__c.split (' ')[0], 
                        LastName = pr.Requester_Name__c.split(' ')[pr.Requester_Name__c.split(' ').size() - 1],
                        Email = pr.Requester_Email__c,
                        AccountId = [SELECT Id, Name FROM Account WHERE Name = 'Sanofi' LIMIT 1].Id,
                        Contact_Type__c = 'Project'
                    );
                    requestToContactInsertMap.put(pr.id,c);
                }
            }		   
        }
        insert requestToContactInsertMap.values();
        
        for(Project_Request__c pr: updateRequestList){
            if(requestToContactInsertMap.get(pr.Id)!= NULL){
                pr.Requester_Contact__c = requestToContactInsertMap.get(pr.Id).id;
            }
        }
        
        update updateRequestList;
    }
}