objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Department_Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Costs__c</fullName>
        <label>Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Monthly_Revenue_Schedule__r.Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Department Revenue Schedules</relationshipLabel>
        <relationshipName>Department_Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue_Schedule__c</fullName>
        <label>Monthly Revenue Schedule</label>
        <referenceTo>Monthly_Revenue_Schedule__c</referenceTo>
        <relationshipLabel>Department Revenue Schedules</relationshipLabel>
        <relationshipName>Department_Revenue_Schedules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Department Revenue Schedules</relationshipLabel>
        <relationshipName>Department_Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department Revenue Schedule</label>
    <nameField>
        <displayFormat>DRS-{0}</displayFormat>
        <label>Department Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Department Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Monthly_Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Costs__c</fullName>
        <label>Cost of Revenue</label>
        <summarizedField>Department_Revenue_Schedule__c.Costs__c</summarizedField>
        <summaryForeignKey>Department_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross__c</fullName>
        <formula>Revenue__c - Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monthly Revenue Schedules</relationshipLabel>
        <relationshipName>Monthly_Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <summarizedField>Product_Revenue_Schedule__c.Revenue__c</summarizedField>
        <summaryForeignKey>Product_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Monthly Revenue Schedule</label>
    <nameField>
        <displayFormat>MRS-{0}</displayFormat>
        <label>Monthly Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityRevenueCostSectionCtrl.cls
/*   Name:          OpportunityRevenueCostSectionCtrl
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          11/2/2017
 *   Description:   Controller for OpportunityRevenueCostSectionCtrl page quering related departmnet revenue records
 *
 *   Updates:
 *      01/15/2018 - Serge Kochanovsky - Added locking system for scheduled records.
 */
public with sharing class OpportunityRevenueCostSectionCtrl {

    public Map<String, Map<String, Department_Revenue_Schedule__c>> revenuesMap { get; private set; }
    public List<Monthly_Revenue_Schedule__c> revenues { get; private set; }
    
    public Map<Id, Boolean> lockedSchedules {
        get {
            Map<Id, Boolean> result = new Map<Id, Boolean>();
            List<RevenueCalculationUtil.LockDateWrapper> lockedDates = RevenueCalculationUtil.lockedDates;
            for (Monthly_Revenue_Schedule__c schedule : revenues) {
                for (RevenueCalculationUtil.LockDateWrapper lockedDate : lockedDates) {
                    if (lockedDate.lockType != 'Costs') {
                        result.put(schedule.Id, false);
                        continue;
                    }
                    Boolean inRange = (lockedDate.startDate != null && lockedDate.endDate != null && schedule.Date__c >= lockedDate.startDate && schedule.Date__c <= lockedDate.endDate)
                        || (lockedDate.startDate != null && lockedDate.endDate == null && schedule.Date__c >= lockedDate.startDate)
                        || (lockedDate.startDate == null && lockedDate.endDate != null && schedule.Date__c <= lockedDate.endDate);
                        
                    if (!result.containsKey(schedule.Id) || !result.get(schedule.Id)) {
                        result.put(schedule.Id, inRange);
                    }
                }
            }
            return result;
        }
        private set;
    }
    
    String opportunityId { get; set; }

    public OpportunityRevenueCostSectionCtrl(ApexPages.StandardController controller) {
        opportunityId = controller.getRecord().Id;
        
        this.revenues = [
            SELECT Revenue__c, Costs__c, Gross__c, Date__c,
                (
                    SELECT Department__r.Name, Costs__c, Monthly_Revenue_Schedule__c
                    FROM Department_Revenue_Schedules__r
                    ORDER BY Department__r.Name
                )
            FROM Monthly_Revenue_Schedule__c
            WHERE Opportunity__c = :opportunityId
            ORDER BY Date__c ASC
        ];
        
        for (Monthly_Revenue_Schedule__c revenue : this.revenues) {
            revenue.Date__c = revenue.Date__c.addMonths(1).toStartofMonth().addDays(-1);
        }
        
        Map<String, Id> depMap = new Map<String, Id>();
        for (Department__c dep : [SELECT Name FROM Department__c]) {
            depMap.put(dep.Name, dep.Id);
        }
        
        List<String> depList = new List<String>(depMap.keySet());
        depList.sort();
        
        this.revenuesMap = new Map<String, Map<String, Department_Revenue_Schedule__c>>();
        for (String depName : depList) {
            if (!this.revenuesMap.containsKey(depName)) {
                this.revenuesMap.put(depName, new Map<String, Department_Revenue_Schedule__c>());
            }
            for (Monthly_Revenue_Schedule__c rev : this.revenues) {
                this.revenuesMap.get(depName).put(String.valueOf(rev.Date__c), new Department_Revenue_Schedule__c(Opportunity__c = opportunityId, Monthly_Revenue_Schedule__c = rev.Id, Department__c = depMap.get(depName)));
                for (Department_Revenue_Schedule__c depRev : rev.Department_Revenue_Schedules__r) {
                    if (depRev.Department__r.Name != depName) {
                        continue;
                    }
                    this.revenuesMap.get(depName).put(String.valueOf(rev.Date__c), depRev);
                }
            }
        }
    }
    
    public void updateDepartmentCost() {
        String nameDate = ApexPages.currentPage().getParameters().get('departmentCostId');
        String cost = ApexPages.currentPage().getParameters().get('departmentCostValue');

        if (String.isEmpty(nameDate) || String.isEmpty(cost)) {
            return;
        }

        Department_Revenue_Schedule__c depSchedule = this.revenuesMap.get(nameDate.split('-:-')[0]).get(nameDate.split('-:-')[1]);
        depSchedule.Costs__c = Decimal.valueOf(cost);
        
        try {
            upsert depSchedule;
            revenuesMap.get(nameDate.split('-:-')[0]).put(nameDate.split('-:-')[1], depSchedule);
        } 
        catch (DmlException ex) {
            System.debug(ex);
        }
    }

}