objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Num__c</fullName>
        <defaultValue>'NA'</defaultValue>
        <label>Invoice #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOC_Data_Configuration__c</fullName>
        <label>DOC Data Configuration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DOC_Data_Licensing__c</fullName>
        <label>DOC Data Licensing</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Managerial sales opportunity forecast override.</description>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Hub</fullName>
                    <default>true</default>
                    <label>Data Hub</label>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>DOC Label</fullName>
                </value>
                <value>
                    <fullName>DOC Track</fullName>
                </value>
                <value>
                    <fullName>GROWTH</fullName>
                </value>
                <value>
                    <fullName>IHME</fullName>
                </value>
                <value>
                    <fullName>ASCO DOC Search</fullName>
                </value>
                <value>
                    <fullName>Service Project Platform</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvoiceAllTest.cls
@isTest
public class InvoiceAllTest {

    @isTest
    public static void TestSetInForecast() {
        
        // Data setup
        Account acc = new Account();
        acc.Name = 'Test 375645';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test353423';
        opp.CloseDate = Date.today();
        opp.Product_Category__c = 'Data Hub';
        opp.Contract_Start__c = Date.today().addMonths(3);
        opp.Contract_End__c = Date.today().addMonths(9);
        opp.Amount = 100000;
        opp.StageName = 'Closed Lost';
        opp.AccountId = acc.Id;
        opp.DOC_Data_Configuration__c = 50;
        opp.DOC_Data_Licensing__c = 50;
        insert opp;
        
        Invoice__c inv1 = new Invoice__c();
        inv1.In_Forecast__c = true;
        inv1.Invoice_Num__c = 'NA';
        inv1.Opportunity__c = opp.Id;
        
        Invoice__c inv2 = new Invoice__c();
        inv2.In_Forecast__c = true;
        inv2.Invoice_Num__c = 'TBD';
        inv2.Opportunity__c = opp.Id;
        
        insert new List<Invoice__c>{ inv1, inv2 };
        
        // Run code
        Test.startTest();
        inv1.Invoice_Num__c = '9998';
        inv2.Invoice_Num__c = '9999';
        update new List<Invoice__c>{ inv1, inv2 };
        Test.stopTest();
        
        // Verify Results
        inv1 = [SELECT In_Forecast__c FROM Invoice__c WHERE Id = :inv1.Id];
        System.assertEquals(false, inv1.In_Forecast__c);
        inv2 = [SELECT In_Forecast__c FROM Invoice__c WHERE Id = :inv2.Id];
        System.assertEquals(false, inv2.In_Forecast__c);
    }
    
}