objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Accrued_Revenue_Formula__c</fullName>
        <formula>IF(Deferred_Revenue__c &lt; 0, ABS(Deferred_Revenue__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accrued Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cumulative_Invoices__c</fullName>
        <label>Cumulative Invoices</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cumulative_Revenue__c</fullName>
        <label>Cumulative Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deferred_Revenue_Formula__c</fullName>
        <formula>IF(Deferred_Revenue__c &gt;= 0, Deferred_Revenue__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deferred Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue__c</fullName>
        <label>Monthly Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoiceListCtrl.cls
/*   Name:          InvoiceListCtrl
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          8/31/2017
 *   Description:   Controller for InvoiceList page quering related invoice records
 *
 *   Updates:
 *      09/04/2017 - added revenue schedule query to get Monthly Revenue and Cumulative Revenue
 */

public with sharing class InvoiceListCtrl {
    public List<Invoice> invoices {get; set;}

    public InvoiceListCtrl(ApexPages.StandardController controller) {

        String opportunityId = controller.getRecord().Id;

        List<Invoice__c> invoiceList = [
            SELECT Accrued_Revenue_Formula__c, Deferred_Revenue_Formula__c, Invoice_Date__c, Invoice_Amount__c,
                Cumulative_Revenue__c, Cumulative_Invoices__c, Monthly_Revenue__c
            FROM Invoice__c
            WHERE Opportunity__c = :opportunityId
            ORDER BY Invoice_Date__c
        ];

        /* 
         * Legacy calculation was here previously, that is the reayon for wrapper class.
         */
        this.invoices = new List<Invoice>();
        for (Invoice__c invoice : invoiceList) {
            Invoice newInvoice = new Invoice();
            if (invoice.Invoice_Date__c != null) {
                newInvoice.name = invoice.Invoice_Date__c.addMonths(1).toStartofMonth().addDays(-1).format();                
            }
        
            newInvoice.monthRevenue = invoice.Monthly_Revenue__c;
            newInvoice.cumulativeRevenue = invoice.Cumulative_Revenue__c;
            newInvoice.cumulativeAmount = invoice.Cumulative_Invoices__c;
            newInvoice.accruedRevenue = invoice.Accrued_Revenue_Formula__c;
            newInvoice.deferredRevenue = invoice.Deferred_Revenue_Formula__c;

            invoices.add(newInvoice);
        }
    }

    private class Invoice {
        public String name {get; set;}
        public Decimal monthRevenue {get; set;}
        public Decimal cumulativeRevenue {get; set;}
        public Decimal cumulativeAmount {get; set;}
        public Decimal accruedRevenue {get; set;}
        public Decimal deferredRevenue {get; set;}
    }
}