objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Invoice_Date__c</fullName>
        <label>Actual Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Num__c</fullName>
        <defaultValue>'NA'</defaultValue>
        <label>Invoice #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sub_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries (Sub-Project)</relationshipLabel>
        <relationshipName>Toggl_Time_Entries1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InvoiceHandler.cls
public with sharing class InvoiceHandler {
    
    public static void UpdateGAAPOnTimeEntries(List<Invoice__c> newList, Map<Id, Invoice__c> oldMap) {
    	
    	Set<Id> oppIds = new Set<Id>();
    	for (Invoice__c newInv : newList) {
    		Invoice__c oldInv = oldMap.get(newInv.Id);
    		if (newInv.Invoice_Num__c != 'NA' && newInv.Invoice_Num__c != 'TBD' && (newInv.Invoice_Num__c != oldInv.Invoice_Num__c || newInv.Actual_Invoice_Date__c != oldInv.Actual_Invoice_Date__c)) {
    			oppIds.add(newInv.Opportunity__c);
    		}
    	}
    	
    	if (oppIds.size() > 0) {
    		List<Toggl_Time_Entry__c> tes = [SELECT Id, Project_Name__c, Account__r.Name, Start_Date__c FROM Toggl_Time_Entry__c 
    											WHERE Project__r.TASKRAY__trOpportunity__c IN :oppIds OR Sub_Project__r.TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__c IN :oppIds];
    		if (tes.size() > 0) {
    			TogglGAAPClassBatch.SetGAAPClass(tes, false);
    		}
    	}
    	
    }
    
}