objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Accrued_Revenue_Formula__c</fullName>
        <formula>IF(Deferred_Revenue__c &lt; 0, ABS(Deferred_Revenue__c), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Accrued Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cumulative_Invoices__c</fullName>
        <label>Cumulative Invoices</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cumulative_Revenue__c</fullName>
        <label>Cumulative Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deferred_Revenue_Formula__c</fullName>
        <formula>IF(Deferred_Revenue__c &gt;= 0, Deferred_Revenue__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Deferred Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Revenue__c</fullName>
        <label>Monthly Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Managerial sales opportunity forecast override.</description>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityBalanceSheetSectionCtrl.cls
/*   Name:          InvoiceListCtrl
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          11/2/2017
 *   Description:   Controller for OpportunityBalanceSheet page quering related invoice records
 */

public with sharing class OpportunityBalanceSheetSectionCtrl {

    public List<Invoice__c> invoices { get; private set; }
    public Boolean isForecasted { get; private set; }

    public OpportunityBalanceSheetSectionCtrl(ApexPages.StandardController controller) {

        String opportunityId = controller.getRecord().Id;
        
        Opportunity opportunity = [
            SELECT IsClosed, In_Forecast__c
            FROM Opportunity
            WHERE Id = :opportunityId
        ];
        this.isForecasted = opportunity.In_Forecast__c;

        this.invoices = [
            SELECT Accrued_Revenue_Formula__c, Deferred_Revenue_Formula__c, Invoice_Date__c, Invoice_Amount__c,
                Cumulative_Revenue__c, Cumulative_Invoices__c, Monthly_Revenue__c
            FROM Invoice__c
            WHERE Opportunity__c = :opportunityId
            ORDER BY Invoice_Date__c
        ];
        
        for (Invoice__c invoice : this.invoices) {
            invoice.Invoice_Date__c = invoice.Invoice_Date__c.addMonths(1).toStartofMonth().addDays(-1);
        }
    }

}