objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Num__c</fullName>
        <defaultValue>'NA'</defaultValue>
        <label>Invoice #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>SF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoiceAllHelper.cls
public class InvoiceAllHelper {

    public static void SetInForecast(List<Invoice__c> newList, Map<Id, Invoice__c> oldMap) {
        
        for (Invoice__c newInv : newList) {
            Invoice__c oldInv = oldMap.get(newInv.Id);
            if ((newInv.Invoice_Num__c != 'NA' && newInv.Invoice_Num__c != 'TBD') && (oldInv.Invoice_Num__c == 'NA' || oldInv.Invoice_Num__c == 'TBD')) {
                newInv.In_Forecast__c = false;
            }
        }
        
    }
    
}