objects/Junction_Kbase__c.object
<CustomObject>
    <fields>
        <fullName>DI_II_Assigned_Date__c</fullName>
        <label>DI-II Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-II Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_II_Completion_Date__c</fullName>
        <label>DI-II Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Fix_Check_Assigned_Date__c</fullName>
        <label>DI-II Fix Check Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Fix_Check_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-II Fix Check Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_II_Fix_Check_Completion_Date__c</fullName>
        <label>DI-II Fix Check Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Fixes_Assigned_Date__c</fullName>
        <label>DI-II Fixes Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Fixes_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-II Fixes Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_II_Fixes_Completion_Date__c</fullName>
        <label>DI-II Fixes Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_II_Reference_Status__c</fullName>
        <label>DI-II Reference Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reference_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DI_I_Assigned_Date__c</fullName>
        <label>DI-I Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-I Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_I_Completion_Date__c</fullName>
        <label>DI-I Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Fix_Check_Assigned_Date__c</fullName>
        <label>DI-I Fix Check Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Fix_Check_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-I Fix Check Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_I_Fix_Check_Completion_Date__c</fullName>
        <label>DI-I Fix Check Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Fixes_Assigned_Date__c</fullName>
        <label>DI-I Fixes Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Fixes_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DI-I Fixes Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DI_I_Fixes_Completion_Date__c</fullName>
        <label>DI-I Fixes Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DI_I_Reference_Status__c</fullName>
        <label>DI-I Reference Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reference_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Extraction_Assigned_Date__c</fullName>
        <label>Extraction Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extraction_Assignee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Extraction Assignee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Junction_Kbases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_Completion_Date__c</fullName>
        <label>Extraction Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extraction_Reference_Status__c</fullName>
        <label>Extraction Reference Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Reference_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kbases_Name__c</fullName>
        <formula>Kbases__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Kbases Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kbases__c</fullName>
        <label>Ref ID</label>
        <referenceTo>Kbase__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LMS_Bucket__c</fullName>
        <label>LMS Bucket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Sub-Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Project must be a sub-project.</errorMessage>
            <filterItems>
                <field>TASKRAY__Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub-Project</value>
            </filterItems>
            <infoMessage>Please select a sub-project.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Junction_Kbases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Junction Kbase</label>
    <nameField>
        <label>Case to Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Kbases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Kbase__c.object
<CustomObject>
    <label>Kbase</label>
    <nameField>
        <label>Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kbases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Reference_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Unassigned</fullName>
        <default>true</default>
        <label>Unassigned</label>
    </customValue>
    <customValue>
        <fullName>Assigned</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting on Tech</fullName>
        <isActive>false</isActive>
        <label>Waiting on Tech</label>
    </customValue>
    <customValue>
        <fullName>Waiting on Questions</fullName>
        <isActive>false</isActive>
        <label>Waiting on Questions</label>
    </customValue>
    <masterLabel>Reference Status</masterLabel>
</GlobalValueSet>

classes/TriggerUtil_JunctionKbase.cls
public class TriggerUtil_JunctionKbase {
    
    
    public static void updateTaskRay(List<Junction_Kbase__c> newJunctions){
        
        List<string> refIds = new List<string>();
        List<id> subProjIds = new List<id>();
        Map<string,junction_kBase__c> refIdJBaseMap = new Map<string,junction_kBase__c>();  
        Set<id> assigneeIDs = new Set<id>();
        For(Junction_Kbase__c j: newJunctions){
            if(j.LMS_Bucket__c != 'Rejected'){
                refIds.add(j.Kbases_Name__c);                
                subProjIds.add(j.TaskRay_Project__c);
                refIdJBaseMap.put(j.Kbases_Name__c,j);
                assigneeIDs.add(j.DI_I_Assignee_Name__c);
                assigneeIDs.add(j.DI_I_Fix_Check_Assignee_Name__c);
                assigneeIDs.add(j.DI_I_Fixes_Assignee_Name__c);
                assigneeIDs.add(j.DI_II_Assignee_Name__c);
                assigneeIDs.add(j.DI_II_Fix_Check_Assignee_Name__c); 
                assigneeIDs.add(j.DI_II_Fixes_Assignee_Name__c);
                assigneeIDs.add(j.Extraction_Assignee_Name__c);
            } 
        }        
        system.debug('assigneeIds size' + assigneeIDs.size());
        List<user> users = [SELECT name FROM user WHERE id IN: assigneeIDs];
        Map<id,user> userMap = new Map<id,user>(users);
        
        List<TASKRAY__trChecklistItem__c> tasks = [
                        SELECT TASKRAY__Project_Task__r.Ref_ID__c, 
                                TASKRAY__Project_Task__r.TASKRAY__Project__c,
                                TASKRAY__Project_Task__r.name,
                                Assigned_Date__c,Completion_Date__c,Reference_Status__c,
                                Assignee_Name__c,name
                                FROM  TASKRAY__trChecklistItem__c WHERE 
                        TASKRAY__Project_Task__r.TASKRAY__Project__c IN: subProjIds AND 
                        Name IN: refIds];
        system.debug(tasks.size() + ' task matches');
        if(tasks.isEmpty()) return;
        For(TASKRAY__trChecklistItem__c ti: tasks){
            system.debug(refIdJBaseMap.get(ti.Name) + ' ' + refIdJBaseMap.get(ti.name).TaskRay_Project__c + ' *&^ ' + ti.TASKRAY__Project_Task__r.TASKRAY__Project__c);
            if(refIdJBaseMap.get(ti.Name) != NULL  
               && refIdJBaseMap.get(ti.name).TaskRay_Project__c == ti.TASKRAY__Project_Task__r.TASKRAY__Project__c){
                system.debug('match found' + ti.TASKRAY__Project_Task__r.name); 
                   Junction_Kbase__c j = refIdJBaseMap.get(ti.name);
                   //we update all tasks with this general information
                   ti.Kbase__c = j.Kbases__c;
                   ti.Junction_Kbase__c = j.id;
                   if(ti.TASKRAY__Project_Task__r.name == 'Extraction'){
                       ti.Assigned_Date__c = j.Extraction_Assigned_Date__c;
                       ti.completion_date__c = j.Extraction_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.Extraction_Assignee_Name__c) != NULL) ? userMap.get(j.Extraction_Assignee_Name__c).name : NULL;
                       ti.Reference_Status__c  = j.Extraction_Reference_Status__c;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-I'){
                       ti.Assigned_Date__c = j.DI_I_Assigned_Date__c;
                       ti.completion_date__c = j.DI_I_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_I_Assignee_Name__c) != NULL) ? userMap.get(j.DI_I_Assignee_Name__c).name : NULL;
                       ti.Reference_Status__c  = j.DI_I_Reference_Status__c;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-I Fixes'){
                       ti.Assigned_Date__c = j.DI_I_Fixes_Assigned_Date__c;
                       ti.completion_date__c = j.DI_I_Fixes_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_I_Fixes_Assignee_Name__c) != NULL) ? userMap.get(j.DI_I_Fixes_Assignee_Name__c).name : NULL;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-I Fix Check'){
                       ti.Assigned_Date__c = j.DI_I_Fix_Check_Assigned_Date__c;
                       ti.completion_date__c = j.DI_I_Fix_Check_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_I_Fix_Check_Assignee_Name__c) != NULL) ? userMap.get(j.DI_I_Fix_Check_Assignee_Name__c).name : NULL;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-II'){
                       ti.Assigned_Date__c = j.DI_II_Assigned_Date__c;
                       ti.completion_date__c = j.DI_II_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_II_Assignee_Name__c) != NULL) ? userMap.get(j.DI_II_Assignee_Name__c).name : NULL;
                       ti.Reference_Status__c  = j.DI_II_Reference_Status__c;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-II Fixes'){
                       ti.Assigned_Date__c = j.DI_II_Fixes_Assigned_Date__c;
                       ti.completion_date__c = j.DI_II_Fixes_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_II_Fixes_Assignee_Name__c) != NULL) ? userMap.get(j.DI_II_Fixes_Assignee_Name__c).name : NULL;
                   }else if(ti.TASKRAY__Project_Task__r.name == 'DI-II Fix Check'){
                       ti.Assigned_Date__c = j.DI_II_Fix_Check_Assigned_Date__c;
                       ti.completion_date__c = j.DI_II_Fix_Check_Completion_Date__c;
                       ti.Assignee_Name__c = (userMap.get(j.DI_II_Fix_Check_Assignee_Name__c) != NULL) ? userMap.get(j.DI_II_Fix_Check_Assignee_Name__c).name : NULL;
                   }
               }
        }
        System.debug('Tasks about to update' + tasks);
        update tasks;
        
        
    }
    
    public static void updateTaskRay(List<Junction_Kbase__c> oldJunctions,List<Junction_Kbase__c> newJunctions){
        
        List<Junction_Kbase__c> junctions = new List<Junction_Kbase__c>();
        For(integer i = 0; i<newJunctions.size(); i++){
            junctions.add(newJunctions[i]);
        }
        
        TriggerUtil_JunctionKbase.updateTaskRay(junctions);
    }

}