objects/Junction_Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <formula>Kbases__r.Extraction_Quantity__c</formula>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Kbases__c</fullName>
        <label>Ref ID</label>
        <referenceTo>Kbase__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Sub_Kbases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Junction Kbase</label>
    <nameField>
        <label>Case to Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Kbases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Kbase__c.object
<CustomObject>
    <fields>
        <fullName>Extraction_Quantity__c</fullName>
        <label>Extraction Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extraction_Task_Description__c</fullName>
        <label>Extraction Task Description</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tables</fullName>
                </value>
                <value>
                    <fullName>Term_Index</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kbase</label>
    <nameField>
        <label>Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kbases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KbaseToJKbase_EXT.cls
public class KbaseToJKbase_EXT {

    public Kbase__c kbase {get; set;}    
    public Id caseId;
    public boolean foundExisting {get;set;}
    public string kBaseRefId {get;set;}
    public boolean searched {get;set;}
    
    private Id existingKbaseId;
    
   	public KbaseToJKbase_EXT(ApexPages.StandardController stdController) {			
    	this.kbase = (Kbase__c)stdController.getRecord();
        this.caseId = ApexPages.currentPage().getParameters().get('caseId');
        this.foundExisting = false;
        this.searched = false;
	}
    
    
    public pageReference KbaseToJKbase() {
        try {
        	Junction_Kbase__c jKbase = new Junction_Kbase__c(Name = 'LEAVE', Case__c=caseId);
            if(!this.foundExisting){ 
            	insert this.kbase;      
				jKbase.Kbases__c = this.kbase.Id;                 
            }
        	else{
            	jKbase.Kbases__c = existingKbaseId;                 
        	}
			
            system.debug(jKbase);
            insert jKbase;
            PageReference pg = new PageReference('/' + jKbase.Id);
			return pg;
        }
        catch(System.DmlException e) {
            system.debug('KbaseToJKbase Exception---' + e.getMessage());
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
    
    public void searchKbase(){       
        this.kBaseRefId = this.kBaseRefId.trim();
        List<Kbase__c> kBaseList = [SELECT Id,Name,Extraction_Quantity__c,Extraction_Task_Description__c FROM Kbase__c WHERE Name like :this.kBaseRefId];
        if(!kBaseList.isEmpty()){
            this.existingKbaseId = kBaseList[0].Id;
            this.kbase = kBaseList[0];
            this.foundExisting = true;
	        this.searched = true;            
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.INFO, 'Found existing Kbase with entered Ref Id.  New Junction Kbase will be associated with the existing Kbase.'));
        }
        else{
			this.kBase = new Kbase__c();
            this.kBase.Name = kBaseRefId;
            this.foundExisting = false;
	        this.searched = true;            
			ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.INFO, 'No existing Kbase found.  A new KBase will be created and the new Junction Kbase associated with it.'));            
        }
    }
}