objects/Junction_Kbase__c.object
<CustomObject>
    <fields>
        <fullName>LMS_Bucket__c</fullName>
        <label>LMS Bucket</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Sub-Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Project must be a sub-project.</errorMessage>
            <filterItems>
                <field>TASKRAY__Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub-Project</value>
            </filterItems>
            <infoMessage>Please select a sub-project.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Junction Kbases</relationshipLabel>
        <relationshipName>Junction_Kbases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Junction Kbase</label>
    <nameField>
        <label>Case to Ref ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Junction Kbases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Digitized__c</fullName>
        <inlineHelpText>[Calculated field] The number of junction kbases associated with a sub-project that are not rejected (i.e. the current number of references accepted during digitization).</inlineHelpText>
        <label># Digitized</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskRaySubprojectBatch.cls
/********************************************************************************************************
*    Name:  TaskRaySubprojectBatch.cls
*    Author:  
*    Date:  6/12/2018
*    
*    Scheduler class: TaskRaySubprojectScheduler.cls
*    Test class: TaskRaySubprojectBatchTest.cls
********************************************************************************************************/

global class TaskRaySubprojectBatch implements Database.Batchable <SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String Query='SELECT Id, Digitized__c FROM TASKRAY__Project__c WHERE TASKRAY__Project_Parent__c != null';
        return Database.getQueryLocator(Query);
    }

    global void execute(Database.BatchableContext bc, List<TASKRAY__Project__c> scope)
    {
        
        List<Junction_Kbase__c> JunctionKbase = [SELECT Id, TaskRay_Project__c FROM Junction_Kbase__c WHERE TaskRay_Project__c IN: scope AND LMS_Bucket__c != 'Rejected'];
        Map<Id, List<Junction_Kbase__c>> JunctionKbaseMap = new Map<Id, List<Junction_Kbase__c>>();
        for(Junction_Kbase__c jk: JunctionKbase) {
            if(!JunctionKbaseMap.containsKey(jk.TaskRay_Project__c))
            {
                List<Junction_Kbase__c> newList = new List<Junction_Kbase__c>();
                newList.add(jk);
                JunctionKbaseMap.put(jk.TaskRay_Project__c, newList);
            } else {
                List<Junction_Kbase__c> exList = JunctionKbaseMap.get(jk.TaskRay_Project__c);
                exList.add(jk);
                JunctionKbaseMap.put(jk.TaskRay_Project__c, exList);
            }
        }
        List<TASKRAY__Project__c> TASKRAYProjectToUpdate = new List<TASKRAY__Project__c>();
        for(TASKRAY__Project__c tp: scope)
        {
            if(JunctionKbaseMap.containsKey(tp.Id))
            {
                List<Junction_Kbase__c> currentTaskProject = JunctionKbaseMap.get(tp.Id);
                Integer JunctionKbaseNumber = currentTaskProject.size();
                tp.Digitized__c = JunctionKbaseNumber;
                TASKRAYProjectToUpdate.add(tp);
            }
        }
        
        if(TASKRAYProjectToUpdate.size() > 0)
            update TASKRAYProjectToUpdate;
    }

    global void finish(Database.BatchableContext bc)
    {
        
    }
}