objects/Monthly_Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Costs__c</fullName>
        <label>Cost of Revenue</label>
        <summarizedField>Department_Revenue_Schedule__c.Costs__c</summarizedField>
        <summaryForeignKey>Department_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross__c</fullName>
        <formula>Revenue__c - Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Monthly Revenue Schedules</relationshipLabel>
        <relationshipName>Monthly_Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <summarizedField>Product_Revenue_Schedule__c.Revenue__c</summarizedField>
        <summaryForeignKey>Product_Revenue_Schedule__c.Monthly_Revenue_Schedule__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Monthly Revenue Schedule</label>
    <nameField>
        <displayFormat>MRS-{0}</displayFormat>
        <label>Monthly Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Forecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Managerial sales opportunity forecast override.</description>
        <label>In Forecast</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpportunityGrossProfitSectionCtrl.cls
/*   Name:          OpportunityGrossProfitSectionCtrl
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          11/1/2017
 *   Description:   Controller for OpportunityGrossProfitSection page quering related revenue records
 */
 
public with sharing class OpportunityGrossProfitSectionCtrl {

    public List<Monthly_Revenue_Schedule__c> revenues { get; private set; }
    public Boolean isForecasted { get; private set; }

    public OpportunityGrossProfitSectionCtrl(ApexPages.StandardController controller) {
        String opportunityId = controller.getRecord().Id;
        
        Opportunity opportunity = [
            SELECT IsClosed, In_Forecast__c, CloseDate, Contract_Start__c, Contract_End__c
            FROM Opportunity
            WHERE Id = :opportunityId
        ];
        this.isForecasted = opportunity.In_Forecast__c;
        
        List<Monthly_Revenue_Schedule__c> mrs = [
            SELECT Date__c 
            FROM Monthly_Revenue_Schedule__c 
            WHERE Opportunity__c = :opportunityId
            ORDER BY Date__c ASC
        ];
        
        Date mrsStart;
        Date mrsEnd;
        
        if(mrs.size() > 0) {
            mrsStart = mrs[0].Date__c;
            mrsEnd = mrs[mrs.size() - 1].Date__c;
        }
        else {
            mrsStart = null;
            mrsEnd = null;
        }
        
        Date closeDate = opportunity.CloseDate != null ? opportunity.CloseDate : Date.today().addYears(-10);
        Date contractStart = opportunity.Contract_Start__c != null ? opportunity.Contract_Start__c.toStartOfMonth() : Date.today().addYears(-10);
        Date contractEnd = opportunity.Contract_End__c != null ? opportunity.Contract_End__c.addMonths(1).toStartOfMonth().addDays(-1) : Date.today().addYears(10);
        Date earliestStart = mrsStart != null ? mrsStart.toStartOfMonth() : Date.today().addYears(-10);
        Date latestEnd = mrsEnd != null ? mrsEnd.addMonths(1).toStartOfMonth().addDays(-1) : Date.today().addYears(10);
        //Date earliestStart = opportunity.Earliest_Start_Date__c != null ? opportunity.Earliest_Start_Date__c.toStartOfMonth() : Date.today().addYears(-10);
        //Date latestEnd = opportunity.Latest_End_Date__c != null ? opportunity.Latest_End_Date__c.addMonths(1).toStartOfMonth().addDays(-1) : Date.today().addYears(10);
        
        this.revenues = [
            SELECT Revenue__c, Costs__c,Gross__c, Date__c
            FROM Monthly_Revenue_Schedule__c
            WHERE Opportunity__c = :opportunityId
            //AND Opportunity__r.In_Forecast__c = true
            //ORDER BY Date__c ASC
                AND ((Opportunity__r.In_Forecast__c = true AND Date__c >= :closeDate) OR (Opportunity__r.In_Forecast__c = false AND Date__c >= :earliestStart AND Date__c <= :latestEnd)) //Date__c >= :contractStart AND Date__c <= :contractEnd))
            ORDER BY Date__c ASC
        ];
        
        for (Monthly_Revenue_Schedule__c revenue : this.revenues) {
            revenue.Date__c = revenue.Date__c.addMonths(1).toStartofMonth().addDays(-1);
        } 
    }

}