objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <displayFormat>SF{0000}</displayFormat>
        <externalId>true</externalId>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor__c.object
<CustomObject>
    <label>Preferred Vendor</label>
    <nameField>
        <label>Preferred Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>PICO_ID__r.TASKRAY__trOpportunity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Vendor</label>
        <referenceTo>Preferred_Vendor__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Due_Date__c</fullName>
        <label>Project Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_s_for_Outsourcing__c</fullName>
        <label>Reason(s) for Outsourcing</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>External expertise required</fullName>
                </value>
                <value>
                    <fullName>Internal resource contraints</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AdobeSign_Total_Estimated_Fees__c</fullName>
        <formula>CASE(LEN( TEXT(Total_Estimated_Fees__c) ),
1, "$" &amp; TEXT(Total_Estimated_Fees__c),
2, "$" &amp; TEXT(Total_Estimated_Fees__c),
3, "$" &amp; TEXT(Total_Estimated_Fees__c),
4, "$" &amp; LEFT(TEXT(Total_Estimated_Fees__c), 1) &amp; "," &amp; RIGHT(TEXT(Total_Estimated_Fees__c), 3),
5, "$" &amp; LEFT(TEXT(Total_Estimated_Fees__c), 2) &amp; "," &amp; RIGHT(TEXT(Total_Estimated_Fees__c), 3),
6, "$" &amp; LEFT(TEXT(Total_Estimated_Fees__c), 3) &amp; "," &amp; RIGHT(TEXT(Total_Estimated_Fees__c), 3),
7, "$" &amp; LEFT(TEXT(Total_Estimated_Fees__c), 1) &amp; "," &amp; MID(TEXT(Total_Estimated_Fees__c), 2,3) &amp; "," &amp; RIGHT(TEXT(Total_Estimated_Fees__c), 3),
null)</formula>
        <label>AdobeSign Total Estimated Fees</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Estimated_Fees__c</fullName>
        <formula>IF( ( ISPICKVAL(Preferred_Vendor__r.Rate_Type__c, "Hourly Rate") || ISPICKVAL(Rate_Type_Override__c, "Hourly Rate Override") ) &amp;&amp; !ISPICKVAL(Rate_Type_Override__c, "Flat Rate Override"), Est_Hours_to_Complete__c * Hourly_Rate__c ,  Flat_Rate__c )</formula>
        <label>Total Estimated Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PICO_ID__c</fullName>
        <label>PICO ID</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>TASKRAY__trOpportunity__r.Opportunity_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

classes/ProcessInstanceStepBatch.cls
/********************************************************************************************************
*    Batch class: ProcessInstanceStepBatch.cls
*    Author:  
*    Date:  6/8/2017
*    
*    Test class:  ProcessInstanceStepBatchTest.cls
*    Scheduled class: ProcessInstanceStepScheduler.cls
********************************************************************************************************/

global class ProcessInstanceStepBatch implements Database.Batchable <SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc){
        Set<String> stepStatusValues = new Set<String>{'Pending'};
        
        //String Query = 'SELECT SELECT Id, NodeStatus, ProcessInstanceId, ProcessInstance.TargetObjectId FROM processinstancenode WHERE nodeStatus IN: stepStatusValues';
        String Query='SELECT ActorId, StepStatus, Actor.Name, Actor.Email, ProcessInstanceId, ProcessInstance.TargetObjectId, ProcessInstance.Status from ProcessInstanceStep WHERE ProcessInstance.Status IN: stepStatusValues';
        return Database.getQueryLocator(Query);
    }

    global void execute(Database.BatchableContext bc, List<ProcessInstanceStep> scope){
        
        //EmailTemplate emailTemplate = [SELECT Id, Body FROM EmailTemplate WHERE DeveloperName = 'Pending_Process'];
        
        Set<Id> ProcessInstanceIds = new Set<Id>();
        for(ProcessInstanceStep  p: scope)
        {
            ProcessInstanceIds.add(p.ProcessInstanceId);
        }
        
        Map<Id, ProcessInstance> ProcessInstanceMap = new Map<Id, ProcessInstance>([SELECT Id, TargetObjectId FROM ProcessInstance WHERE Id IN: ProcessInstanceIds]);
        Map<Id, Id> ProcessInstanceToTargetObj = new Map<Id, Id>();
        for(Id myId: ProcessInstanceMap.keySet()){
            processInstanceToTargetObj.put(myId, processInstanceMap.get(myId).TargetObjectId);
        }
        Map<Id, Preferred_Vendor_Request__c> TargetObjIdToPVR = new Map<Id, Preferred_Vendor_Request__c>(
            [SELECT Id, PICO_ID__c, PICO_ID__r.Name, PICO_ID__r.TASKRAY__trAccount__r.Id, PICO_ID__r.TASKRAY__trAccount__r.Name, 
             PICO_ID__r.TASKRAY__trOpportunity__c, PICO_ID__r.Opportunity_ID__c, PICO_ID__r.TASKRAY__trOpportunity__r.Id , 
             PICO_ID__r.TASKRAY__trOpportunity__r.Name, Preferred_Vendor__c, Preferred_Vendor__r.Name, Total_Estimated_Fees__c, 
             AdobeSign_Total_Estimated_Fees__c, Reason_s_for_Outsourcing__c, Project_Due_Date__c 
             FROM Preferred_Vendor_Request__c 
             WHERE Id IN: processInstanceToTargetObj.values()]);
        system.debug('processInstanceToObject---' + TargetObjIdToPVR);
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        string BaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        String oPrefix = Preferred_Vendor_Request__c.sobjecttype.getDescribe().getKeyPrefix();
        
        for(ProcessInstanceStep  p: scope)
        {
            ProcessInstance pi = ProcessInstanceMap.get(p.ProcessInstanceId);
            String sPrefix = String.valueOf(pi.TargetObjectId);            
            if(oPrefix == sPrefix.substring(0, 3) && !String.isEmpty(p.Actor.Email)) 
            {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {p.Actor.Email});
                email.setSaveAsActivity(false);
                email.setTargetObjectId(p.ActorId);
                //email.setTemplateId(emailTemplate.Id);
                email.Subject = 'Preferred Vendor Request - Pending Approval';
                email.setHtmlBody('<p>This <a href="' + BaseURL + '/' + pi.TargetObjectId + '" >record</a> needs your review.</p>' + 
                                  'PICO ID: <a href="' + BaseURL + '/' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__c + '">' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.Name + '</a><br/>' + 
                                  'Client Name: <a href="' + BaseURL + '/' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.TASKRAY__trAccount__r.Id + '">' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.TASKRAY__trAccount__r.Name + '</a><br/>' +
                                  'SFID: <a href="' + BaseURL + '/' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.TASKRAY__trOpportunity__c + '">' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.Opportunity_ID__c + '</a><br/>' + 	
                                  'Opportunity Name: <a href="' + BaseURL + '/' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.TASKRAY__trOpportunity__r.Id + '">' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).PICO_ID__r.TASKRAY__trOpportunity__r.Name + '</a><br/>' + 
                                  'Preferred Vendor: <a href="' + BaseURL + '/' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).Preferred_Vendor__c + '">' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).Preferred_Vendor__r.Name + '</a><br/>' + 
                                  'Total Estimated Fees: ' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).AdobeSign_Total_Estimated_Fees__c + '<br/>' +
                                  'Reason(s) for Outsourcing: ' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).Reason_s_for_Outsourcing__c + '<br/>' +
                    			  'Project Due Date: ' + TargetObjIdToPVR.get(processInstanceToTargetObj.get(pi.Id)).Project_Due_Date__c);
                mails.add(email);
                //Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            }
        }
        if(!Test.isRunningTest())
            Messaging.sendEmail(mails);
        
    }

    global void finish(Database.BatchableContext bc){
        
    }
}