objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>DRE_Point_of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Preferred_Vendor_Staff__c.Preferred_Vendor__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Preferred_Vendor_Staff__c</referenceTo>
        <relationshipLabel>Preferred Vendors</relationshipLabel>
        <relationshipName>Preferred_Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly Rate</fullName>
                </value>
                <value>
                    <fullName>Flat Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preferred Vendor</label>
    <nameField>
        <label>Preferred Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Est_Hours_to_Complete__c</fullName>
        <inlineHelpText>Please only specify estimated hours for non-flat rate projects</inlineHelpText>
        <label>Est. Hours to Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Preferred_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Vendor</label>
        <referenceTo>Preferred_Vendor__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <formula>TEXT( Preferred_Vendor__r.Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>PO No. Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DRE_Point_of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DRE Point of Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This user is not an authorized DRE Point of Contact.</errorMessage>
            <filterItems>
                <field>User.DRE_Point_of_Contact__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Preferred_Vendor_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PICO_ID__c</fullName>
        <label>PICO ID</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Preferred_Vendor_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Vendor__c</fullName>
        <label>Preferred Vendor</label>
        <referenceTo>Preferred_Vendor__c</referenceTo>
        <relationshipLabel>Preferred Vendor Staff</relationshipLabel>
        <relationshipName>Preferred_Vendor_Staff</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preferred Vendor Staff</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Vendor Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Archive_1_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Archive 1 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PreferredVendorAllHandlerTest.cls
@isTest
public class PreferredVendorAllHandlerTest{
    
    private static testmethod void testPreferredVendorAll1(){
        //test data setup
        Account acc = new Account();
        acc.Name = 'Test923736';
        insert acc;
        
        Contact newContact = new Contact();
        newContact.LastName = 'LastName';
        newContact.Email = 'test@email.com';
        newContact.AccountId = acc.Id;
        insert newContact;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Contract_End__c = Date.today().addDays(-1);
        opp.Name = 'Test218927';
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today().addDays(30);
        insert opp;
        
        TASKRAY__Project__c proj = new TASKRAY__Project__c();
        proj.TASKRAY__Status__c = false;
        proj.Contract_Archive_1_Days__c = false;
        proj.TASKRAY__trOpportunity__c = opp.Id;
        
        insert proj;
        
        Preferred_Vendor__c PreferredVendor = new Preferred_Vendor__c();
        PreferredVendor.Hourly_Rate__c = 20;
        PreferredVendor.Rate_Type__c = 'Hourly Rate';
        
        insert PreferredVendor;
        
        Preferred_Vendor_Staff__c pvs = new Preferred_Vendor_Staff__c();
        pvs.Email__c = 'Test@emailtestalert.com';
        pvs.Preferred_Vendor__c = PreferredVendor.Id;
        
        insert pvs;
        
        Preferred_Vendor_Request__c pvr = new Preferred_Vendor_Request__c();
        pvr.PICO_ID__c = proj.Id;
        pvr.Status__c = 'PO No. Requested';
        pvr.Preferred_Vendor__c = PreferredVendor.Id;
        pvr.Est_Hours_to_Complete__c = 20;
        pvr.DRE_Point_of_Contact__c = UserInfo.getUserId();
        insert pvr;
        
        //Submit Quote for Approval
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(pvr.id);
        Approval.ProcessResult result = Approval.process(app);
        
        //ProcessInstance ActiveProcessInstance = [SELECT Id, Status FROM ProcessInstance WHERE TargetObjectId =: pvr.Id AND Status = 'Pending' LIMIT 1];
        //system.debug('====> ' + ActiveProcessInstance.Status);
                
        
        Test.startTest();
            Preferred_Vendor__c pv = [SELECT Id, Rate_Type__c FROM Preferred_Vendor__c WHERE Id =: PreferredVendor.Id];
            pv.DRE_Point_of_Contact__c = pvs.Id;
            pv.Rate_Type__c = 'Flat Rate';
            pv.Hourly_Rate__c = null;        	
            update pv;
            
            Preferred_Vendor_Request__c pvrUpdated = [SELECT Id, Status__c  FROM Preferred_Vendor_Request__c WHERE Preferred_Vendor__c =: pv.Id];
        	
        
            System.assertEquals('Rejected', pvrUpdated.Status__c);
        Test.stopTest();  
        
            
    }
    
    
    private static testmethod void testPreferredVendorAll2(){
        //test data setup
        Account acc = new Account();
        acc.Name = 'Test923736';
        insert acc;
        
        Contact newContact = new Contact();
        newContact.LastName = 'LastName';
        newContact.Email = 'test@email.com';
        newContact.AccountId = acc.Id;
        insert newContact;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Contract_End__c = Date.today().addDays(-1);
        opp.Name = 'Test218927';
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today().addDays(30);
        insert opp;
        
        TASKRAY__Project__c proj = new TASKRAY__Project__c();
        proj.TASKRAY__Status__c = false;
        proj.Contract_Archive_1_Days__c = false;
        proj.TASKRAY__trOpportunity__c = opp.Id;

        insert proj;
        
        Preferred_Vendor__c PreferredVendor = new Preferred_Vendor__c();
        PreferredVendor.Hourly_Rate__c = 20;
        PreferredVendor.Rate_Type__c = 'Hourly Rate';
        insert PreferredVendor;
        
        Preferred_Vendor_Staff__c pvs = new Preferred_Vendor_Staff__c();
        pvs.Email__c = 'Test@emailtestalert.com';
        pvs.Preferred_Vendor__c = PreferredVendor.Id;
        
        insert pvs;
        
        Preferred_Vendor_Request__c pvr = new Preferred_Vendor_Request__c();
        pvr.PICO_ID__c = proj.Id;
        pvr.Status__c = 'In Approval Process';
        pvr.Preferred_Vendor__c = PreferredVendor.Id;
        pvr.Est_Hours_to_Complete__c = 20;
        pvr.DRE_Point_of_Contact__c = UserInfo.getUserId();
        insert pvr;
        
        Preferred_Vendor_Request__c pvr1 = new Preferred_Vendor_Request__c();
        pvr1.PICO_ID__c = proj.Id;
        pvr1.Status__c = 'PO No. Requested';
        pvr1.Preferred_Vendor__c = PreferredVendor.Id;
        pvr1.Est_Hours_to_Complete__c = 20;
        pvr1.DRE_Point_of_Contact__c = UserInfo.getUserId();
        insert pvr1;
        
        //Submit Quote for Approval
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(pvr.id);
        Approval.ProcessResult result = Approval.process(app);
        
        //ProcessInstance ActiveProcessInstance = [SELECT Id, Status FROM ProcessInstance WHERE TargetObjectId =: pvr.Id AND Status = 'Pending' LIMIT 1];
        //system.debug('====> ' + ActiveProcessInstance.Status);
                
        
        Test.startTest();
            Preferred_Vendor__c pv = [SELECT Id, Rate_Type__c FROM Preferred_Vendor__c WHERE Id =: PreferredVendor.Id];
            pv.DRE_Point_of_Contact__c = pvs.Id;
            //pv.Rate_Type__c = 'Flat Rate';
            //pv.Hourly_Rate__c = null;
            
            update pv;
            
            List<Preferred_Vendor_Request__c>  pvrUpdated = [SELECT Id, Status__c  FROM Preferred_Vendor_Request__c WHERE Preferred_Vendor__c =: pv.Id];
            for(Preferred_Vendor_Request__c pvre: pvrUpdated )
                System.assertEquals('Rejected', pvre.Status__c);
        Test.stopTest();      
    }
    
}