objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly Rate</fullName>
                </value>
                <value>
                    <fullName>Flat Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preferred Vendor</label>
    <nameField>
        <label>Preferred Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Est_Hours_to_Complete__c</fullName>
        <inlineHelpText>Please only specify estimated hours for non-flat rate projects</inlineHelpText>
        <label>Est. Hours to Complete</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Preferred_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Vendor</label>
        <referenceTo>Preferred_Vendor__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <formula>TEXT( Preferred_Vendor__r.Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PICO_ID__c</fullName>
        <label>PICO ID</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Archive_1_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Archive 1 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProcessInstanceStepBatchTest.cls
/********************************************************************************************************
*    Name:  ProcessInstanceStepBatchTest.cls
*    Author:  
*    Date:  6/8/2017
*    
*    Batch class: ProcessInstanceStepBatch.cls
*    Scheduled class: ProcessInstanceStepScheduler.cls
********************************************************************************************************/

@isTest
public class ProcessInstanceStepBatchTest {

    public static testMethod void testProcessInstanceStepBatch(){
        
        //test data setup
        Account acc = new Account();
        acc.Name = 'Test923736';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Contract_End__c = Date.today().addDays(-1);
        opp.Name = 'Test218927';
        opp.StageName = 'Prospecting';
        opp.CloseDate = Date.today().addDays(30);
        insert opp;
        
        TASKRAY__Project__c proj = new TASKRAY__Project__c();
        proj.TASKRAY__Status__c = false;
        proj.Contract_Archive_1_Days__c = false;
        proj.TASKRAY__trOpportunity__c = opp.Id;
        insert proj;
        
        Preferred_Vendor__c pv = new Preferred_Vendor__c();
        pv.Name = 'Preferred Vendor Name';
        pv.Rate_Type__c = 'Hourly Rate';
        pv.Hourly_Rate__c = 100;
        insert pv;
        
        Preferred_Vendor_Request__c pvr = new Preferred_Vendor_Request__c();
        pvr.PICO_ID__c = proj.Id;
        pvr.Preferred_Vendor__c = pv.Id;
        pvr.Est_Hours_to_Complete__c = 5;
        insert pvr;
        
        Test.startTest();
            ProcessInstanceStepBatch p = new ProcessInstanceStepBatch();
            database.executebatch(p);
            
            
        Test.stopTest();
    }
}