objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <displayFormat>SF{0000}</displayFormat>
        <externalId>true</externalId>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>TASKRAY__trOpportunity__r.Opportunity_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GAAP_Class__c</fullName>
        <label>GAAP Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work in Progress</fullName>
                </value>
                <value>
                    <fullName>Cost of Revenue</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>General &amp; Administrative</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Development</fullName>
                </value>
                <value>
                    <fullName>2.0 Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TogglGAAPClassBatchTest.cls
@isTest
public class TogglGAAPClassBatchTest{
    
    private static testmethod void testGAAPClassBatch1() {

        Account acc = new Account();
        acc.Name = 'Doctor Evidence';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test926345';
        opp.AccountId = acc.Id;
        opp.StageName = 'Qualification/Prospecting';
        opp.CloseDate = Date.today();
        insert opp;
        
        TASKRAY__Project__c proj = new TASKRAY__Project__c();
        proj.Name = 'CE Admin/Internal';
        proj.TASKRAY__trOpportunity__c = opp.Id;
        insert proj;
        
        Toggl_Time_Entry__c timeEntry = new Toggl_Time_Entry__c();
        timeEntry.Account__c = acc.Id;
        timeEntry.Project_Name__c = 'CE Admin/Internal';
        insert timeEntry;
        
        Test.StartTest();
            Test.setMock(HttpCalloutMock.class.class, new TogglToSalesforceMock(''));
            TogglGAAPClassBatch d = new TogglGAAPClassBatch(); 
            database.executebatch(d, 1);
        Test.StopTest();
        
        timeEntry = [SELECT Project__c, GAAP_Class__c, Opportunity__c FROM Toggl_Time_Entry__c WHERE Id = :timeEntry.Id];
        System.assertEquals(proj.Id, timeEntry.Project__c);
        System.assertEquals(opp.Id, timeEntry.Opportunity__c);
        System.assertEquals('Sales & Marketing', timeEntry.GAAP_Class__c);
    }
    
    private static testmethod void testGAAPClassBatch2() {

        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test926345';
        opp.AccountId = acc.Id;
        opp.StageName = 'Qualification/Prospecting';
        opp.CloseDate = Date.today();
        insert opp;
        
        opp = [SELECT Opportunity_ID__c FROM Opportunity WHERE Id = :opp.Id];
        
        TASKRAY__Project__c proj = new TASKRAY__Project__c();
        proj.Name = opp.Opportunity_ID__c;// + ' | SNF-Neur-025';
        proj.TASKRAY__trOpportunity__c = opp.Id;
        insert proj;
        
        Toggl_Time_Entry__c timeEntry = new Toggl_Time_Entry__c();
        timeEntry.Account__c = acc.Id;
        timeEntry.Project_Name__c = opp.Opportunity_ID__c + ' | SNF-Neur-025';
        insert timeEntry;
        
        Test.StartTest();
            Test.setMock(HttpCalloutMock.class.class, new TogglToSalesforceMock(''));
            TogglGAAPClassBatch d = new TogglGAAPClassBatch(); 
            database.executebatch(d, 1);
        Test.StopTest();
        
        timeEntry = [SELECT Project__c, GAAP_Class__c, Opportunity__c FROM Toggl_Time_Entry__c WHERE Id = :timeEntry.Id];
        system.debug('timeEntry---' + timeEntry);
        System.assertEquals(proj.Id, timeEntry.Project__c);
        System.assertEquals(opp.Id, timeEntry.Opportunity__c);
        System.assertEquals('Work in Progress', timeEntry.GAAP_Class__c);
    }
}