objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Archived_Date__c</fullName>
        <label>Archived Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Archived_Reason__c</fullName>
        <label>Archived Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete: Delivered (modified from original scope)</fullName>
                </value>
                <value>
                    <fullName>Complete: Delivered feasibility assessment</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Client strategy change</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Infeasible timeline</fullName>
                </value>
                <value>
                    <fullName>Discontinued: Strategic internal decision</fullName>
                </value>
                <value>
                    <fullName>Contract Terminated</fullName>
                </value>
                <value>
                    <fullName>Contract Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Archive_14_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Archive 14 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Archive_1_Days__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Archive 1 Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The opportunity a sub-project is associated with (if it is tied to a legacy opportunity and new opportunity, this represents the new opportunity).</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

classes/Project_Completion_Batch.cls
/*   Name:          Project_Completion_Batch
 *   Developer:     CLOUD MINE CONSULTING
 *   Date:          5/2/2018
 *   Description:   Batch Class to Manage date-based notifications for Projects and Sub-Projects
 *   Test Class:	Project_Completion_Batch_Test             
 */

global class Project_Completion_Batch implements Database.Batchable<TASKRAY__Project__c > {

    private Set<Id> projIdSet = new Set<Id>(); //projectIdList to limit testing to certain projects
    private static final string ARCHIVED_REASON = 'Contract Expired';
    
    global Project_Completion_Batch(){
    }
    
    global Project_Completion_Batch(Set<Id> testProjectIdSet){
        if(testProjectIdSet != NULL)
	        projIdSet = testProjectIdSet;
    }
    
	global List<TASKRAY__Project__c > start(Database.BatchableContext BC) {
        string idSetFilter = (!projIdSet.isEmpty()) ? 'ID IN:projIdSet' : '';
        string days_14_from_now = string.valueof(date.today().adddays(14));
        string query = 'SELECT TASKRAY__trOpportunity__r.Contract_End__c, TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c, Contract_Archive_14_Days__c,Contract_Archive_1_Days__c,TASKRAY__Project_Parent__c,TASKRAY__Status__c,Archived_Date__c,Archived_Reason__c ' +
                'FROM TASKRAY__Project__c WHERE (( (TASKRAY__trOpportunity__c != NULL AND TASKRAY__trOpportunity__r.Contract_End__c = ' + days_14_from_now + ') OR (TASKRAY__Project_Parent__c != NULL AND TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c = ' + days_14_from_now + ')) AND TASKRAY__Status__c = FALSE AND Contract_Archive_14_Days__c = FALSE)' + 
                'OR (( (TASKRAY__trOpportunity__c != NULL AND TASKRAY__trOpportunity__r.Contract_End__c = YESTERDAY) OR (TASKRAY__Project_Parent__c != NULL AND TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c = YESTERDAY)) AND TASKRAY__Status__c = FALSE AND Contract_Archive_1_Days__c = FALSE) ' + idSetFilter;
        system.debug(query);
        return database.query(query);
        /*
		return [SELECT TASKRAY__trOpportunity__r.Contract_End__c, TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c, Contract_Archive_14_Days__c,Contract_Archive_1_Days__c,TASKRAY__Project_Parent__c 
                FROM TASKRAY__Project__c WHERE (( (TASKRAY__trOpportunity__c != NULL AND TASKRAY__trOpportunity__r.Contract_End__c = NEXT_N_DAYS:14) OR (TASKRAY__Project_Parent__c != NULL AND TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c = NEXT_N_DAYS:14)) AND TASKRAY__Status__c = FALSE AND Contract_Archive_14_Days__c = FALSE) 
                OR (( (TASKRAY__trOpportunity__c != NULL AND TASKRAY__trOpportunity__r.Contract_End__c = YESTERDAY) OR (TASKRAY__Project_Parent__c != NULL AND TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c = YESTERDAY)) AND TASKRAY__Status__c = TRUE AND Contract_Archive_1_Days__c = FALSE)];*/
    }

    global void execute(Database.BatchableContext BC, List<TASKRAY__Project__c > projectsList) {
		List<TASKRAY__Project__c> projectsToUpdate = new List<TASKRAY__Project__c>();
        for(TASKRAY__Project__c proj: projectsList){
            //project logic
            if(proj.TASKRAY__Project_Parent__c == NULL){
                //14 days in future logic
                if(proj.TASKRAY__trOpportunity__r.Contract_End__c == date.today().addDays(14) && proj.Contract_Archive_14_Days__c == FALSE){
                    proj.Contract_Archive_14_Days__c = TRUE;
                    projectsToUpdate.add(proj);
                }//1 day ago logic
                else if(proj.TASKRAY__trOpportunity__r.Contract_End__c < date.today() && proj.Contract_Archive_1_Days__c == FALSE){
					proj.Contract_Archive_1_Days__c = TRUE;
                    //archive project logic
                    proj.TASKRAY__Status__c = TRUE;
                    proj.Archived_Date__c = proj.TASKRAY__trOpportunity__r.Contract_End__c;
                    proj.Archived_Reason__c = ARCHIVED_REASON;
                    projectsToUpdate.add(proj);                    
                }                                    
            }//sub-project logic
            else if(proj.TASKRAY__Project_Parent__c != NULL){
                //14 days in future logic
                if(proj.TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c == date.today().addDays(14) && proj.Contract_Archive_14_Days__c == FALSE){
                    proj.Contract_Archive_14_Days__c = TRUE;
                    projectsToUpdate.add(proj);                    
                }//1 day ago logic
                else if(proj.TASKRAY__Project_Parent__r.TASKRAY__trOpportunity__r.Contract_End__c < date.today() && proj.Contract_Archive_1_Days__c == FALSE){
					proj.Contract_Archive_1_Days__c = TRUE;
                    //archive project logic
                    proj.TASKRAY__Status__c = TRUE;
                    proj.Archived_Date__c = proj.TASKRAY__trOpportunity__r.Contract_End__c;
                    proj.Archived_Reason__c = ARCHIVED_REASON;        
                    projectsToUpdate.add(proj);                    
                }            
            }            
        }
        system.debug('projectsListToUpdate---' + projectsToUpdate);
        update projectsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {

    }    
    
}