objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Approval Process</fullName>
                </value>
                <value>
                    <fullName>PO No. Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted for Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Number__c</fullName>
        <inlineHelpText>Preferred Vendor Request PO Number to be issued by DRE finance.</inlineHelpText>
        <label>PO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SOW_AdobeSignController.cls
public with sharing class SOW_AdobeSignController 
{
    public Boolean showError {get; set;}
    public Boolean redirectToUrl {get; set;}
    public String recordId {get; set;}

	public SOW_AdobeSignController(ApexPages.StandardController stdController) 
    {
        showError = false;
        redirectToUrl = false;

		recordId = ((Preferred_Vendor_Request__c)stdController.getRecord()).Id;

        List<Preferred_Vendor_Request__c> prefVendorRequestList =
            [
                SELECT Id, Status__c, PO_Number__c 
                FROM Preferred_Vendor_Request__c 
                WHERE Id = :recordId
            ];

        if(prefVendorRequestList.size() > 0)
        {
            if(prefVendorRequestList[0].Status__c == 'Approved' && prefVendorRequestList[0].PO_Number__c != null)
            {
                redirectToUrl = true;
            }
            else 
            {
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, Label.SOW_ErrorMessage);
                ApexPages.addMessage(msg);
                showError = true;
            }
        }
        else
        {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, Label.NoRecordsFound);
            ApexPages.addMessage(msg);
            showError = true;
        }
	}

    public PageReference RedirectToUrl()
    {
        if(redirectToUrl == true && showError == false)
        {
            String url = '/apex/echosign_dev1__AgreementTemplateProcess?masterId=' + recordId + '&templateId=a2A0f000017slz5';
            PageReference retURL = new PageReference(url);
            retURL.setRedirect(true);
            return retURL;
        }
        
        return null;
    }

    public PageReference GoBack()
    {
        return new PageReference('/' + recordId);  
    }
}