objects/Preferred_Vendor__c.object
<CustomObject>
    <label>Preferred Vendor</label>
    <nameField>
        <label>Preferred Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferred Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Preferred_Vendor_Request__c.object
<CustomObject>
    <fields>
        <fullName>Preferred_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Vendor</label>
        <referenceTo>Preferred_Vendor__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PICO_ID__c</fullName>
        <label>PICO ID</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Preferred Vendor Requests</relationshipLabel>
        <relationshipName>Preferred_Vendor_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preferred Vendor Request</label>
    <nameField>
        <displayFormat>PVR-{000000}</displayFormat>
        <label>Preferred Vendor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Vendor Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SOW_AdobeSignControllerTest.cls
@isTest
private class SOW_AdobeSignControllerTest 
{	
	@isTest static void test_method_one() 
    {
        // Data Setup
        TASKRAY__Project__c taskRayProject = new TASKRAY__Project__c();
        insert taskRayProject;

        Preferred_Vendor__c prefVendor = new Preferred_Vendor__c();
        prefVendor.Name = 'testName';
        insert prefVendor;

        Preferred_Vendor_Request__c prefVendorRequest = new Preferred_Vendor_Request__c();
        prefVendorRequest.PICO_ID__c = taskRayProject.Id;
        prefVendorRequest.Preferred_Vendor__c = prefVendor.Id;
        insert prefVendorRequest;

        ApexPages.StandardController sc = new ApexPages.StandardController(prefVendorRequest);

		// Run Code
        SOW_AdobeSignController ctrl = new SOW_AdobeSignController(sc);

        ctrl.redirectToUrl = true;
        ctrl.showError = false;
        ctrl.RedirectToUrl();
	}
}