objects/Project_Request__c.object
<CustomObject>
    <fields>
        <fullName>Problem__c</fullName>
        <label>Problem</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Name__c</fullName>
        <label>Requester Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>TaskRay Project link.</description>
        <inlineHelpText>This field will auto-populate upon TaskRay Project creation. Please leave this field blank. This field is intended to serve as a link.</inlineHelpText>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Project Requests</relationshipLabel>
        <relationshipName>Project_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Object created to receive client requests from the DOC Data portal.</description>
    <label>Project Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Project Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Feedback_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Kick_Off_Meeting__c</fullName>
        <inlineHelpText>The date on which the client kick off meeting actually occurred</inlineHelpText>
        <label>Client Kick Off Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Name - Filtered by Related Account</description>
        <inlineHelpText>The primary client propositioning or sponsoring this project. This field should be consistent for all sub-projects underneath a parent project.</inlineHelpText>
        <label>Primary Contact Name</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Contact must be associated to the assigned Account &amp; must have their contact type set to 'Project'</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.TASKRAY__trAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Contact_Type__c</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <inlineHelpText>Enter the general problem or project stakes that are addressed by the project, i.e. WHY is the client asking for DRE to perform the work?</inlineHelpText>
        <label>Problem</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <inlineHelpText>The research question to be investigated or objective of the given sub-project (must be unique across sub-projects if different services are intended to answer different aspects of a larger research question).</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Name__c</fullName>
        <label>Requester Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <inlineHelpText>Enter a description of the work being performed to address the client-stated need for the project, i.e. HOW is DRE solving the business problem as requested by the client?</inlineHelpText>
        <label>Solution</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <inlineHelpText>Enter a description of how the project, when successfully completed, will benefit the client stakeholders. Be specific regarding the previously stated Problem.</inlineHelpText>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientFeedbackRequestedBtnTest.cls
@isTest
public class ClientFeedbackRequestedBtnTest{
    
    private static testmethod void testClientFeedbackRequest(){
    
        Account acc1 = new Account();
        acc1.Name = 'Sanofi';
        insert acc1;
        
        Account acc = new Account();
        acc.Name = 'Test Acc';
        insert acc;
        
        Contact cnt = new Contact();
        cnt.FirstName = 'Contact';
        cnt.LastName = 'Test';
        cnt.AccountId = acc.Id;
        cnt.Email = 'testemail@testemail.com';
        insert cnt;
        
        TASKRAY__Project__c tProject = new TASKRAY__Project__c();
        tProject.TASKRAY__trAccount__c = acc.Id;
        tProject.Client_Kick_Off_Meeting__c = (Date.Today()).addDays(-5);
        tProject.Contact_Name__c = cnt.Id;
        tProject.Requester_Name__c = 'Contact Test';
        tProject.Question__c = 'question question question question';
        tProject.Problem__c = 'problem problem problem problem';
        tProject.Solution__c = 'Solution solution solution solution';
        tProject.Value__c = 'Value Value Value Value Value Value';
        insert tProject;
        
        /*Project_Request__c pr = new Project_Request__c();
        pr.Requester_Contact__c = cnt.Id;
        pr.TaskRay_Project__c = tProject.Id;
        pr.Requester_Name__c = 'Contact Test';
        pr.Question__c = 'question question question question';
        pr.Problem__c = 'problem problem problem problem';
        pr.Solution__c = 'Solution solution solution solution';
        pr.Value__c = 'Value Value Value Value Value Value';
        insert pr;*/
        
        Apexpages.StandardController sc = new Apexpages.StandardController(tProject);
        ClientFeedbackRequestedBtn CFR = new ClientFeedbackRequestedBtn(sc);
        Test.StartTest();
            CFR.SendEmail();
            CFR.BackToTRProject();
        Test.StopTest();
        
        TASKRAY__Project__c currentTProject = [SELECT Id, Client_Feedback_Requested__c FROM TASKRAY__Project__c WHERE Id =: tProject.Id];
        System.assertEquals(true, currentTProject.Client_Feedback_Requested__c );
       
    }
}