objects/RME_Value_Framework_Email_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Template_Unique_Name__c</fullName>
        <label>Template Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RME Value Framework Email Settings</label>
    <pluralLabel>RME Value Framework Email Settings</pluralLabel>
</CustomObject>

objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Feedback_Requested_Date__c</fullName>
        <label>Client Feedback Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Feedback_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Name - Filtered by Related Account</description>
        <inlineHelpText>The primary client propositioning or sponsoring this project. This field should be consistent for all sub-projects underneath a parent project.</inlineHelpText>
        <label>Primary Contact Name</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Contact must be associated to the assigned Account &amp; must have their contact type set to 'Project'</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.TASKRAY__trAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.Contact_Type__c</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClientFeedbackRequestedBtn.cls
public class ClientFeedbackRequestedBtn {

    private final TASKRAY__Project__c TASKRAYproj;
    private List<TASKRAY__Project__c> currentTASKRAYProject;

    public ClientFeedbackRequestedBtn(ApexPages.StandardController stdController) {
        this.TASKRAYproj = (TASKRAY__Project__c)stdController.getRecord();
        currentTASKRAYProject = [SELECT Id, Contact_Name__c, Contact_Name__r.Id, Contact_Name__r.Email, Client_Feedback_Requested__c FROM TASKRAY__Project__c WHERE Id =: TASKRAYproj.Id LIMIT 1];   
    }

    public void SendEmail() {
        
        //List<TASKRAY__Project__c> currentTASKRAYProject = [SELECT Id, Client_Feedback_Requested__c FROM TASKRAY__Project__c WHERE Id =: currentProjectRequest[0].TaskRay_Project__c LIMIT 1];
        List<RME_Value_Framework_Email_Settings__mdt> RMEValueFramework = [SELECT Template_Unique_Name__c FROM RME_Value_Framework_Email_Settings__mdt WHERE Label = 'Client Feedback Requested' LIMIT 1];
        if( RMEValueFramework.size() == 1 )
        {
            String templateUniqueName = RMEValueFramework[0].Template_Unique_Name__c;
            List<EmailTemplate> emailtemplateList = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: templateUniqueName ];
    
            if(currentTASKRAYProject.size() > 0 && emailtemplateList.size() > 0)
            {
                if (currentTASKRAYProject[0].Client_Feedback_Requested__c == true) {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Email Previously Sent.');
                    ApexPages.addMessage(myMsg);
                    return;
                }
                
                if (currentTASKRAYProject[0].Contact_Name__c == null) {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Primary Contact Name is not set.');
                    ApexPages.addMessage(myMsg);
                    return;
                }
                
                if (currentTASKRAYProject[0].Contact_Name__r.Email == null) {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Primary Contact Name does not have an email.');
                    ApexPages.addMessage(myMsg);
                    return;
                }
                
                try {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
                    mail.setSenderDisplayName('Test Response to Client Request');         
                    mail.setTargetObjectId(currentTASKRAYProject[0].Contact_Name__c);
                    mail.setWhatId(currentTASKRAYProject[0].Id);
                    mail.setTemplateId(emailtemplateList[0].Id);
                    if(!Test.isRunningTest())
                        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
                } catch(exception ex) {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage());
                    ApexPages.addMessage(myMsg);  
                    
                }
                
                try {
                    currentTASKRAYProject[0].Client_Feedback_Requested__c = true;
                    currentTASKRAYProject[0].Client_Feedback_Requested_Date__c = Date.Today();
                    update currentTASKRAYProject;
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Email was successfully sent!');
                    ApexPages.addMessage(myMsg);
                } catch(dmlexception e) {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
                    ApexPages.addMessage(myMsg);
                }
            }
        }
    }
    
    public PageReference BackToTRProject() {
        PageReference pageRef = new PageReference('/' + TASKRAYproj.Id);
        pageRef.setRedirect(true);
        return pageRef;
    }
}