objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Services_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Client Services Rep</description>
        <inlineHelpText>The Associate Account Director assigned to the project or sub-project</inlineHelpText>
        <label>Associate Account Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_Development__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Learning &amp; Development representative for this sub-project (i.e. user responsible for training client on DOC platforms)</inlineHelpText>
        <label>Learning &amp; Development</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsTZpq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meth_Rep_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Methodology Lead</description>
        <inlineHelpText>The primary user responsible for all aspects related to methodological decisions &amp; directing the work work of the team.</inlineHelpText>
        <label>Methodologist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Role__c</fullName>
        <label>Assigned Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TaskRay_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/TaskRay_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Other (Not on Project Team)</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Reviewer</fullName>
    </customValue>
    <customValue>
        <fullName>Associate Account Director</fullName>
    </customValue>
    <customValue>
        <fullName>Learning &amp; Development</fullName>
    </customValue>
    <customValue>
        <fullName>Methodologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Clinical Data Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Search Strategist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Manager</fullName>
        <isActive>false</isActive>
        <label>Ontology Manager</label>
    </customValue>
    <customValue>
        <fullName>VP Consulting Services</fullName>
        <isActive>false</isActive>
        <label>VP Consulting Services</label>
    </customValue>
    <customValue>
        <fullName>Meth Rep #3</fullName>
        <isActive>false</isActive>
        <label>Meth Rep #3</label>
    </customValue>
    <customValue>
        <fullName>Head of Clinical Ops and Data Integrity</fullName>
        <isActive>false</isActive>
        <label>Head of Clinical Ops and Data Integrity</label>
    </customValue>
    <customValue>
        <fullName>Data Integrity Team Lead</fullName>
        <isActive>false</isActive>
        <label>Data Integrity Team Lead</label>
    </customValue>
    <customValue>
        <fullName>Statistician</fullName>
        <isActive>false</isActive>
        <label>Statistician</label>
    </customValue>
    <customValue>
        <fullName>Chief Medical Officer</fullName>
        <isActive>false</isActive>
        <label>Chief Medical Officer</label>
    </customValue>
    <customValue>
        <fullName>Head of Library Operations</fullName>
        <isActive>false</isActive>
        <label>Head of Library Operations</label>
    </customValue>
    <customValue>
        <fullName>VP Client Services</fullName>
        <isActive>false</isActive>
        <label>VP Client Services</label>
    </customValue>
    <customValue>
        <fullName>Librarian Lead</fullName>
        <isActive>false</isActive>
        <label>Librarian Lead</label>
    </customValue>
    <customValue>
        <fullName>GH QMI</fullName>
        <isActive>false</isActive>
        <label>GH QMI</label>
    </customValue>
    <masterLabel>TaskRay Roles</masterLabel>
</GlobalValueSet>

classes/UpdateRoleCheckListHelperTest.cls
@isTest
public class UpdateRoleCheckListHelperTest {
    
     static testMethod void updateRoleTest_WithUpdateTrigger()
    {
		String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        
        RecordType rtype = [Select Name, Id From RecordType 
                  where sObjectType='TASKRAY__Project__c' and isActive=true AND RecordType.Name = 'Sub-Project' LIMIT 1];
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        uniqueName = orgId + dateString + randomInt;

		List<User> usersToInsert = new List<User>();
        User u2 = new User( Alias = 'newUser', Email='newuser@testorg.com',
         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
         LocaleSidKey='en_US', ProfileId = p.Id,
         TimeZoneSidKey='America/Los_Angeles', Username = uniqueName + '@test' + orgId + '.org');
        usersToInsert.add(u2);
        
        randomInt = Integer.valueOf(math.rint(math.random()*1000000)); 
        uniqueName = orgId + dateString + randomInt;
        User u1 = new User(Alias = uniqueName.substring(18, 23),Email = uniqueName + '@test' + orgId + '.org',EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',Username = uniqueName + '@test' + orgId + '.org');
        usersToInsert.add(u1);
        
        randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        uniqueName = orgId + dateString + randomInt;
        User u3 = new User(Alias = uniqueName.substring(18, 23),Email = uniqueName + '@test' + orgId + '.org',EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',Username = uniqueName + '@test' + orgId + '.org');
        usersToInsert.add(u3);        

        randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        uniqueName = orgId + dateString + randomInt;
        User u4 = new User(Alias = uniqueName.substring(18, 23),Email = uniqueName + '@test' + orgId + '.org',EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',Username = uniqueName + '@test' + orgId + '.org');
        usersToInsert.add(u4);
        
        randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        uniqueName = orgId + dateString + randomInt;
        User u5 = new User(Alias = uniqueName.substring(18, 23),Email = uniqueName + '@test' + orgId + '.org',EmailEncodingKey='UTF-8',LastName='Testing',LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',Username = uniqueName + '@test' + orgId + '.org');
        usersToInsert.add(u5);
		insert usersToInsert;
        
		TASKRAY__Project__c project = new TASKRAY__Project__c();
		project.Name='ProjectFromApex';
		project.OwnerId= u1.Id;//Owner
		project.RecordTypeId=rtype.Id;
		project.Client_Services_Rep__c= u2.Id;//User1
		project.Learning_Development__c= u3.Id;//User2
		project.Meth_Rep_1__c= u4.Id;//User3                                                 
		insert project; 

		TASKRAY__Project_Task__c ptask = new TASKRAY__Project_Task__c(Name = 'Task To update',
                                                                     TASKRAY__Project__c= project.Id,
                                                                     Assigned_Role__c = 'Learning & Development');  
		insert ptask;
     
		System.Test.startTest();

			TASKRAY__trChecklistItem__c checkListItem = new TASKRAY__trChecklistItem__c( Name = 'CheckMate2',
																						TASKRAY__Project_Task__c = ptask.Id,
																						Assigned_Role__c = 'Methodologist'
																					);
			insert checkListItem;

		System.Test.stopTest();

		checkListItem = [Select Id, TASKRAY__trOwner__c from TASKRAY__trChecklistItem__c Where ID =: checkListItem.Id];
		System.assert(checkListItem.TASKRAY__trOwner__c != null);
	}
    
}