objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Client associated with the project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Role__c</fullName>
        <label>Assigned Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TaskRay_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Tasks</relationshipLabel>
        <relationshipName>trTaskAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/TaskRay_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Other (Not on Project Team)</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Reviewer</fullName>
    </customValue>
    <customValue>
        <fullName>Associate Account Director</fullName>
    </customValue>
    <customValue>
        <fullName>Learning &amp; Development</fullName>
    </customValue>
    <customValue>
        <fullName>Methodologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Clinical Data Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Search Strategist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Manager</fullName>
        <isActive>false</isActive>
        <label>Ontology Manager</label>
    </customValue>
    <customValue>
        <fullName>VP Consulting Services</fullName>
        <isActive>false</isActive>
        <label>VP Consulting Services</label>
    </customValue>
    <customValue>
        <fullName>Meth Rep #3</fullName>
        <isActive>false</isActive>
        <label>Meth Rep #3</label>
    </customValue>
    <customValue>
        <fullName>Head of Clinical Ops and Data Integrity</fullName>
        <isActive>false</isActive>
        <label>Head of Clinical Ops and Data Integrity</label>
    </customValue>
    <customValue>
        <fullName>Data Integrity Team Lead</fullName>
        <isActive>false</isActive>
        <label>Data Integrity Team Lead</label>
    </customValue>
    <customValue>
        <fullName>Statistician</fullName>
        <isActive>false</isActive>
        <label>Statistician</label>
    </customValue>
    <customValue>
        <fullName>Chief Medical Officer</fullName>
        <isActive>false</isActive>
        <label>Chief Medical Officer</label>
    </customValue>
    <customValue>
        <fullName>Head of Library Operations</fullName>
        <isActive>false</isActive>
        <label>Head of Library Operations</label>
    </customValue>
    <customValue>
        <fullName>VP Client Services</fullName>
        <isActive>false</isActive>
        <label>VP Client Services</label>
    </customValue>
    <customValue>
        <fullName>Librarian Lead</fullName>
        <isActive>false</isActive>
        <label>Librarian Lead</label>
    </customValue>
    <customValue>
        <fullName>GH QMI</fullName>
        <isActive>false</isActive>
        <label>GH QMI</label>
    </customValue>
    <masterLabel>TaskRay Roles</masterLabel>
</GlobalValueSet>

classes/TriggerUtil_ChecklistItemTest.cls
@IsTest
private class TriggerUtil_ChecklistItemTest {

    @IsTest
    static void testRollupTaskDate() {
        
        //Cloud Mine Consulting---12/21/17
        //Standard User does not have the Taskray Permission Sets and is causing test failures
        //not sure why Standard User is being used
		//Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        Profile p = [SELECT Id FROM Profile WHERE Name='Ops / Meth / Production Lead'];        

//        Id roleId = [select Id from UserRole where Name='Other (Not on Project Team)'].Id;
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
         
        User u = new User(Alias = uniqueName.substring(18, 23),
                          Email = uniqueName + '@test' + orgId + '.org',
                          EmailEncodingKey='UTF-8',
                          LastName='Testing',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',
                          ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          Username = uniqueName + '@test' + orgId + '.org' /*, UserRoleId=roleId */);

        insert u;
        

        System.runAs(u) {
			Account a = new Account(Name='test account');
    	    insert a;
            Id tpRecId = Schema.SObjectType.TASKRAY__Project__c.getRecordTypeInfosByName().get('Sub-Project').getRecordTypeId();
    
            TASKRAY__Project__c taskP = new TASKRAY__Project__c(TASKRAY__trAccount__c=a.Id, RecordTypeId=tpRecId);
            insert taskp;
            
            TASKRAY__Project_Task__c pt = new TASKRAY__Project_Task__c(TASKRAY__trAccount__c=a.Id, TASKRAY__Project__c=taskP.Id, Assigned_Role__c = 'Other (Not on Project Team)');
            insert pt;
            
			TASKRAY__trChecklistGroup__c taskG = new 	TASKRAY__trChecklistGroup__c(Name='Standard');
			insert taskG;
            
            TASKRAY__trChecklistItem__c tc = new TASKRAY__trChecklistItem__c(Assigned_Date__c = System.today() - 1, TASKRAY__Project_Task__c=pt.id, TASKRAY__trOwner__c=u.Id, Assigned_Role__c='Other (Not on Project Team)', TASKRAY__trChecklistGroup__c=taskG.Id);
            insert tc;          
            
            //simulated a database update with two separate objects as this utility function was commented in the trigger
            //bellow code is the base functionality
            /*tc.Assigned_Date__c = System.today(); 
            tc.Completion_Date__c = System.today()+10;
            update tc;*/
            
            //the code bellow should be deleted for correct testing if the TriggerUtil_ChecklistItem is used in the trigger            
            list<TASKRAY__trChecklistItem__c> tcListOld = new list<TASKRAY__trChecklistItem__c>();
            tcListOld.add(tc);
            
            TASKRAY__trChecklistItem__c tc1 = new TASKRAY__trChecklistItem__c(Assigned_Date__c = System.today(), TASKRAY__Project_Task__c=pt.id, TASKRAY__trOwner__c=u.Id, Assigned_Role__c='Other (Not on Project Team)', TASKRAY__trChecklistGroup__c=taskG.Id);
            insert tc1;
            list<TASKRAY__trChecklistItem__c> tcListNew = new list<TASKRAY__trChecklistItem__c>();
            tcListNew.add(tc1);
            
            TriggerUtil_ChecklistItem.rollupTaskDate(tcListOld, tcListNew);
            //end of code that should be deleted
        }
        

        
    }
    
    
}