objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Toggl_Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Duration_Computed__c</fullName>
        <formula>(End_Date__c  - Start_Date__c) * 24</formula>
        <label>Duration Computed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Toggl Time Entries</relationshipLabel>
        <relationshipName>Toggl_Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toggl Time Entry</label>
    <nameField>
        <label>Toggl Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toggl Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TogglTimeEntriesBatch.cls
global  with sharing class TogglTimeEntriesBatch implements Database.Batchable<sObject> 
{       
    global Database.querylocator start(Database.BatchableContext BC) 
    {
        String queryString = 'SELECT Id, TASKRAY__Project_Parent__c, Total_Actual_Project_Time__c FROM TASKRAY__Project__c';

        return Database.getQueryLocator(queryString);
    }

    global void execute(Database.BatchableContext BC, List<SObject> records) 
    {
        List<TASKRAY__Project__c> taskRayProjectList = (List<TASKRAY__Project__c>)records;

        Set<Id> taskRayProjectSet = new Set<Id>();

        for(TASKRAY__Project__c taskRayProject : taskRayProjectList)
        {
            taskRayProjectSet.add(taskRayProject.Id);
        }
        
        List<Toggl_Time_Entry__c> projectTimeEntryList =    
            [
                SELECT Id, Duration_Computed__c, Project__c
                FROM Toggl_Time_Entry__c
                WHERE Project__c IN :taskRayProjectSet
            ];

        Map<String, Decimal> projectToTotalActualProjectTimeMap = new Map<String, Decimal>();

        for(Toggl_Time_Entry__c projectTimeEntry : projectTimeEntryList)
        {
            if(projectTimeEntry.Duration_Computed__c != null)
            {
                if(projectToTotalActualProjectTimeMap.get(projectTimeEntry.Project__c) == null)
                {
                    projectToTotalActualProjectTimeMap.put(projectTimeEntry.Project__c, projectTimeEntry.Duration_Computed__c);
                }
                else
                {
                    projectToTotalActualProjectTimeMap.put(projectTimeEntry.Project__c, projectToTotalActualProjectTimeMap.get(projectTimeEntry.Project__c) + projectTimeEntry.Duration_Computed__c);
                }
            }
        }

        List<Toggl_Time_Entry__c> subProjectTimeEntryList = 
            [
                SELECT Id, Duration_Computed__c, Project__c, Project__r.TASKRAY__Project_Parent__c
                FROM Toggl_Time_Entry__c
                WHERE Project__r.TASKRAY__Project_Parent__c IN :taskRayProjectSet
            ];

        for(Toggl_Time_Entry__c projectTimeEntry : subProjectTimeEntryList)
        {
            if(projectTimeEntry.Duration_Computed__c != null)
            { 
                if(projectToTotalActualProjectTimeMap.get(projectTimeEntry.Project__r.TASKRAY__Project_Parent__c) == null)
                {
                    projectToTotalActualProjectTimeMap.put(projectTimeEntry.Project__r.TASKRAY__Project_Parent__c, projectTimeEntry.Duration_Computed__c);
                }
                else
                {
                    projectToTotalActualProjectTimeMap.put(projectTimeEntry.Project__r.TASKRAY__Project_Parent__c, projectToTotalActualProjectTimeMap.get(projectTimeEntry.Project__r.TASKRAY__Project_Parent__c) + projectTimeEntry.Duration_Computed__c);
                }
            }
        }       

        for(TASKRAY__Project__c taskRayProject : taskRayProjectList)
        {
            if (projectToTotalActualProjectTimeMap.containsKey(taskRayProject.Id)) {
                taskRayProject.Total_Actual_Project_Time__c = projectToTotalActualProjectTimeMap.get(taskRayProject.Id);
            } else {
                taskRayProject.Total_Actual_Project_Time__c = 0;
            }
        }

        update taskRayProjectList;
    }
    
    global void finish(Database.BatchableContext BC) 
    {

    }   
}