objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Dir_Library_Operations__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head of Library Operations</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7njs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chief Medical Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nji</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Services_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Client Services Rep</description>
        <inlineHelpText>The Associate Account Director assigned to the project or sub-project</inlineHelpText>
        <label>Associate Account Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consulting_Services_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User responsible for performing any analyses for this sub-project.</inlineHelpText>
        <label>Analytics Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consulting_Services_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statistician</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Integrity_TL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Integrity Team Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nkg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_TL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Extraction Team Lead</description>
        <inlineHelpText>The primary user managing timelines &amp; resources for the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nkv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GH_QMI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GH QMI</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nlK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_of_Analytics__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Head of Analytics</description>
        <inlineHelpText>User responsible for reviewing any analyses for this sub-project.</inlineHelpText>
        <label>Analytics Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nlA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_of_Clinical_Operations_and_Data_Int__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head of Clinical Ops and Data Integrity</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsKeMb</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_Development__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Learning &amp; Development representative for this sub-project (i.e. user responsible for training client on DOC platforms)</inlineHelpText>
        <label>Learning &amp; Development</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsTZpq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Librarian_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for all aspects related to the literature search (i.e. writing search strings, executing search, etc.)</inlineHelpText>
        <label>Sr. Search Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meth_Rep_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Methodology Lead</description>
        <inlineHelpText>The primary user responsible for all aspects related to methodological decisions &amp; directing the work work of the team.</inlineHelpText>
        <label>Methodologist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meth_Rep_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Methodology Associate</description>
        <inlineHelpText>The secondary user responsible for all aspects related to methodological decisions &amp; directing the work work of the team.</inlineHelpText>
        <label>Sr. Clinical Data Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ontology_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for all aspects related to ontology.</inlineHelpText>
        <label>Ontology Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ontology_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ontology Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsKeMM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for retrieving full-texts after title/abstract screening.</inlineHelpText>
        <label>Operations Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nk2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Scientist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Principal Scientist</description>
        <inlineHelpText>The user primarily responsible for all client engagement.</inlineHelpText>
        <label>Principal Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Client_Services__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Client Services</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Consulting_Services__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Consulting Services</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7njT</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Role__c</fullName>
        <label>Assigned Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TaskRay_Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
</CustomObject>

globalValueSets/TaskRay_Roles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Other (Not on Project Team)</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics Reviewer</fullName>
    </customValue>
    <customValue>
        <fullName>Associate Account Director</fullName>
    </customValue>
    <customValue>
        <fullName>Learning &amp; Development</fullName>
    </customValue>
    <customValue>
        <fullName>Methodologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Associate</fullName>
    </customValue>
    <customValue>
        <fullName>Principal Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Project Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Clinical Data Specialist</fullName>
    </customValue>
    <customValue>
        <fullName>Sr. Search Strategist</fullName>
    </customValue>
    <customValue>
        <fullName>Ontology Manager</fullName>
        <isActive>false</isActive>
        <label>Ontology Manager</label>
    </customValue>
    <customValue>
        <fullName>VP Consulting Services</fullName>
        <isActive>false</isActive>
        <label>VP Consulting Services</label>
    </customValue>
    <customValue>
        <fullName>Meth Rep #3</fullName>
        <isActive>false</isActive>
        <label>Meth Rep #3</label>
    </customValue>
    <customValue>
        <fullName>Head of Clinical Ops and Data Integrity</fullName>
        <isActive>false</isActive>
        <label>Head of Clinical Ops and Data Integrity</label>
    </customValue>
    <customValue>
        <fullName>Data Integrity Team Lead</fullName>
        <isActive>false</isActive>
        <label>Data Integrity Team Lead</label>
    </customValue>
    <customValue>
        <fullName>Statistician</fullName>
        <isActive>false</isActive>
        <label>Statistician</label>
    </customValue>
    <customValue>
        <fullName>Chief Medical Officer</fullName>
        <isActive>false</isActive>
        <label>Chief Medical Officer</label>
    </customValue>
    <customValue>
        <fullName>Head of Library Operations</fullName>
        <isActive>false</isActive>
        <label>Head of Library Operations</label>
    </customValue>
    <customValue>
        <fullName>VP Client Services</fullName>
        <isActive>false</isActive>
        <label>VP Client Services</label>
    </customValue>
    <customValue>
        <fullName>Librarian Lead</fullName>
        <isActive>false</isActive>
        <label>Librarian Lead</label>
    </customValue>
    <customValue>
        <fullName>GH QMI</fullName>
        <isActive>false</isActive>
        <label>GH QMI</label>
    </customValue>
    <masterLabel>TaskRay Roles</masterLabel>
</GlobalValueSet>

classes/UpdateRoleHelper.cls
public class UpdateRoleHelper {
    
    public UpdateRoleHelper(){}
    
    public static void updateRole(List<TASKRAY__Project_Task__c> oldValues, List<TASKRAY__Project_Task__c> newValues )
    {
        
        
        List<TASKRAY__Project_Task__c> tasksToUpdate = new List<TASKRAY__Project_Task__c>();
    
            // The value of the role
            String assignedRole ;
        
        	// The name of the role
        	
        	String roleName;
            
            // The value of project field to be querried
            String projectField;
            
            // Holds the id of projects
            List<id> projectIds = new List<id>();
            
            // Get the tasks and the related subproject
            for(TASKRAY__Project_Task__c task: newValues)
                {
                    projectIds.add(task.TASKRAY__Project__c);
                    tasksToUpdate.add(task);
                }
        
        	
			//query related projects
						
        	List<TASKRAY__Project__c> relatedProjectList = [SELECT client_services_rep__c, consulting_services_lead__c,Learning_Development__c, 
                                                            consulting_services_rep__c, associate_dir_library_operations__c, 
                                                            librarian_lead__c, operations_associate__c, gh_qmi__c, 
                                                            meth_rep_1__c, meth_rep_2__c, extraction_tl__c, 
                                                            head_of_analytics__c, vp_client_services__c, principal_scientist__c,
                                                            vp_consulting_services__c, cmo__c, data_integrity_tl__c, ontology_lead__c,
                                                            Ontology_Manager__c, Head_of_Clinical_Operations_and_Data_Int__c
                                                            FROM TASKRAY__Project__c WHERE Id IN :projectIds] ; 
        	//For loop
        	for(Integer i=0 ;i <newValues.size(); i++)
            {       
        	//If The new role is Other or task is Completed or the assigned role is empty:  Don't run the trigger
            if(newValues[i].Assigned_Role__c == 'Other (Not on Project Team)' || newValues[i].TASKRAY__trCompleted__c == true || newValues[i].Assigned_Role__c == null)
            {
                return;
            }  
            
            // If there is no change in the role
            if( oldValues != null && (oldValues[i].Assigned_Role__c == newValues[i].Assigned_Role__c))
            {
                return;
            }
                        
            // If the trigger is update
            if(oldValues != null)
                {
                    System.debug('before true ');
                    System.debug( newValues[i].Assigned_Role__c);
                    System.debug( oldValues[i].Assigned_Role__c);
                    System.debug('after true ');
                    // If the assigned Role is changed, assign its value to assignRole
                    if((oldValues[i].Assigned_Role__c != newValues[i].Assigned_Role__c))
                        {
                            System.debug('This should not be printed if the role is other ' + newValues[i].Assigned_Role__c);
                            assignedRole = String.valueOf(newValues[i].Assigned_Role__c);
                            System.debug('The value of the assigned role: ' + assignedRole);
                        }
                    else
                    {
                    	return;
                    }
                }
        	// Trigger is Insert
        	else{
                	System.debug('inside else ');
            		assignedRole = String.valueOf(newValues[i].Assigned_Role__c);
                	System.debug('assigned role ' + assignedRole);
        		}
                    
            //get the api name for the label using the assigned role string
            Map<String, Schema.SObjectField> projectFields = Schema.SObjectType.TASKRAY__Project__c.fields.getMap();
            
            for(String key: projectFields.KeySet())
                {
                    system.debug('the assigned role: ' + assignedRole );
                    system.debug('the label:  ' + projectFields.get(key).getDescribe().getLabel());
                    System.debug('The Key is : ' + key);
                    if(assignedRole == projectFields.get(key).getDescribe().getLabel())
                    {
                        projectField = key;
                        
                        roleName = projectFields.get(key).getDescribe().getLabel();
                        //Exit loop if we find the api name
                        break; 
                    }
                }
            
            for(TASKRAY__Project__c pr : relatedProjectList)
                {
                    if(tasksToUpdate[i].TASKRAY__Project__c == pr.Id )
                    {
                        id idtoUpdate2 = (Id)pr.Get(projectField);
                            if(idtoUpdate2 == null)
                            {
                               tasksToUpdate[i].addError('The role \'' + roleName + '\' you have chosen is not assigned to a user on the sub-project. Please assign it in Project Team section of the sub-project.');
                 
                            }
                        tasksToUpdate[i].OwnerId = idtoUpdate2;
                    }
                }   
            }
        for(TASKRAY__Project_Task__c tsks : tasksToUpdate)
        {
        	System.debug('the list of tasks' + tsks);
        }	
    }

}