objects/TASKRAY__Project__c.object
<CustomObject>
    <fields>
        <fullName>Associate_Dir_Library_Operations__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head of Library Operations</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7njs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chief Medical Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nji</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Services_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Client Services Rep</description>
        <inlineHelpText>The Associate Account Director assigned to the project or sub-project</inlineHelpText>
        <label>Associate Account Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consulting_Services_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User responsible for performing any analyses for this sub-project.</inlineHelpText>
        <label>Analytics Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consulting_Services_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statistician</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Integrity_TL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Integrity Team Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nkg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraction_TL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Extraction Team Lead</description>
        <inlineHelpText>The primary user managing timelines &amp; resources for the project.</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nkv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GH_QMI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GH QMI</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nlK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_of_Analytics__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Head of Analytics</description>
        <inlineHelpText>User responsible for reviewing any analyses for this sub-project.</inlineHelpText>
        <label>Analytics Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nlA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_of_Clinical_Operations_and_Data_Int__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Head of Clinical Ops and Data Integrity</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsKeMb</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Librarian_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for all aspects related to the literature search (i.e. writing search strings, executing search, etc.)</inlineHelpText>
        <label>Sr. Search Strategist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meth_Rep_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Methodology Lead</description>
        <inlineHelpText>The primary user responsible for all aspects related to methodological decisions &amp; directing the work work of the team.</inlineHelpText>
        <label>Methodologist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meth_Rep_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly, Methodology Associate</description>
        <inlineHelpText>The secondary user responsible for all aspects related to methodological decisions &amp; directing the work work of the team.</inlineHelpText>
        <label>Sr. Clinical Data Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ontology_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for all aspects related to ontology.</inlineHelpText>
        <label>Ontology Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ontology_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ontology Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_ProjectsKeMM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for retrieving full-texts after title/abstract screening.</inlineHelpText>
        <label>Operations Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7nk2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Scientist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly: Principal Scientist</description>
        <inlineHelpText>The user primarily responsible for all client engagement.</inlineHelpText>
        <label>Principal Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Client_Services__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Client Services</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VP_Consulting_Services__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>VP Consulting Services</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TaskRay_Projects7njT</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Parent Projects</description>
        <label>Project</label>
    </recordTypes>
</CustomObject>

classes/AddUsersToProjectTeamHelper.cls
public class AddUsersToProjectTeamHelper {
    
	
    public AddUsersToProjectTeamHelper(){}
    
    public static void updateProjectTaskTeam(List<TASKRAY__Project__c> oldProjects, List<TASKRAY__Project__c> newProjects)
    {
        List<Id> projectIds = new List<Id>();
        for(TASKRAY__Project__c pr : newProjects)
        {
           projectIds.add(pr.Id);
        }
        
        List<TASKRAY__trContributor__c> teamMembers = [SELECT Id, TASKRAY__Project__c, TASKRAY__User__c FROM TASKRAY__trContributor__c WHERE TASKRAY__Project__c IN :projectIds];
                
        Set<Id> NewteamMembersIds = new Set<Id>();
		List<TASKRAY__trContributor__c> TeamMemberListToUpdate = new List<TASKRAY__trContributor__c>();
        Set<Id> teamMemberIds = new Set<Id>();
        
    	for (TASKRAY__trContributor__c member : teamMembers)
    		{
        		teamMemberIds.add(member.TASKRAY__User__c);
    		}
        
		//start of the loop
        Schema.SObjectType objType = newProjects.getSObjectType(); 
    
        Map<String, Schema.SObjectField> M = Schema.SObjectType.TASKRAY__Project__c.fields.getMap();
        
        for(integer i =0; i< newProjects.size() ; i++)
        {
             
            for (String str : M.keyset())
                {	 
                    try 
                        {	 
                            if(newProjects[i].get(str) != oldProjects[i].get(str) && newProjects[i].get(str) !=null )
                              {
                                system.debug('******The value has changed!!!! ' + str + ' ' + M.get(str).getDescribe().getLabel() ); 
                                TASKRAY__trContributor__c teamMember = new TASKRAY__trContributor__c();
                                teamMember.TASKRAY__User__c = (Id)newProjects[i].get(str); //Value of the Field//
                                System.debug('The user is ' + teamMember.TASKRAY__User__c);
                                teamMember.TASKRAY__Project__c = newProjects[i].Id;
                                System.debug('The project is is ' + teamMember.TASKRAY__Project__c);
                                 
                                  if(!teamMemberIds.contains(teamMember.TASKRAY__User__c) && !NewteamMembersIds.contains(teamMember.TASKRAY__User__c) )
                                    {
                                        System.debug('The user to be added ' + teamMember.TASKRAY__User__c);
                                        NewteamMembersIds.add(teamMember.TASKRAY__User__c);
                                        TeamMemberListToUpdate.add(teamMember);
                                    } 
                              } 
                        } 
                
                    catch (Exception e) 
                        { 
                            System.debug('Error: ' + e); 
                        }
                }      
             //End Of the loop   
                
			}
        
    	try {
                	System.debug('The list is: ' + TeamMemberListToUpdate);
    				insert TeamMemberListToUpdate;
        	}
        catch(Exception e)
            {
            		System.debug('Error: ' + e);
        	}
    }
    
   public static void insertProjectCreateTaskTeam(List<TASKRAY__Project__c> newProjects)
    {
        TASKRAY__Project__c newProject = newProjects[0];
        Set<Id> NewteamMembersIds = new Set<Id>();
		List<TASKRAY__trContributor__c> TeamMemberListToUpdate = new List<TASKRAY__trContributor__c>();
        
        //Setup the list of roles
        Set<String> roles = new Set<String>{
           	'client_services_rep__c', 'consulting_services_lead__c', 'consulting_services_rep__c', 
            'associate_dir_library_operations__c', 'librarian_lead__c', 'operations_associate__c', 'gh_qmi__c',
            'meth_rep_1__c', 'meth_rep_2__c', 'extraction_tl__c', 'head_of_analytics__c',
            'vp_client_services__c', 'principal_scientist__c','vp_consulting_services__c', 'cmo__c', 'data_integrity_tl__c',
                'ontology_lead__c','ontology_manager__c','head_of_clinical_operations_and_data_int__c'};
                
        TASKRAY__Project__c projectObject = new TASKRAY__Project__c(); // This takes all available fields from the required object. 	

		Schema.SObjectType objType = projectObject.getSObjectType(); 

		Map<String, Schema.SObjectField> M = Schema.SObjectType.TASKRAY__Project__c.fields.getMap(); 
		
        // start loop
        for(TASKRAY__Project__c project : newProjects)
        {
            for (String str : M.keyset())
                {	 
                    try 
                        {
                            if( roles.contains(str) && project.get(str) != null )
                              {
                                system.debug('Inside If ' + str + ' ' + M.get(str).getDescribe().getLabel() ); 
                                // here goes more code
                                TASKRAY__trContributor__c teamMember = new TASKRAY__trContributor__c();
                                 
                                teamMember.TASKRAY__User__c = (Id)project.get(str); //Value of the Field//
                                System.debug('The user is ' + teamMember.TASKRAY__User__c);
                                teamMember.TASKRAY__Project__c = project.Id;
                                System.debug('The project is is ' + teamMember.TASKRAY__Project__c);
                                if(!NewteamMembersIds.contains(teamMember.TASKRAY__User__c))
                                    {
                                        NewteamMembersIds.add(teamMember.TASKRAY__User__c);
                                        TeamMemberListToUpdate.add(teamMember);
                                    } 
                              } 
                        } 
                
                    catch (Exception e) 
                        { 
                            System.debug('Error: ' + e); 
                        } 
                }
        }
        //end of loop
            try {
    		insert TeamMemberListToUpdate;
        }
        catch(Exception e){
            System.debug('Error: ' + e);
        }

    }

}